### ISSUE TITLE
Demand points-to test crashes(TestAgainstSimpleDriver.java)

### ISSUE THREAD

**Issue by enochii** [wala/WALA#1139]
When I run the `TestAgainstSimpleDriver.main` [here](https://github.com/wala/WALA/blob/master/com.ibm.wala.core/src/test/java/com/ibm/wala/demandpa/driver/TestAgainstSimpleDriver.java), it crashes. Here is the error message:

```shell
=======---------------=============
ANALYZING Ldemandpa/TestArraySetIter


Exception in thread "main" com.ibm.wala.util.debug.UnimplementedError
	at com.ibm.wala.util.debug.Assertions.UNREACHABLE(Assertions.java:46)
	at com.ibm.wala.demandpa.flowgraph.SimpleDemandPointerFlowGraph$StatementVisitor.visitLoadMetadata(SimpleDemandPointerFlowGraph.java:1248)
	at com.ibm.wala.ssa.SSALoadMetadataInstruction.visit(SSALoadMetadataInstruction.java:64)
	at com.ibm.wala.demandpa.flowgraph.SimpleDemandPointerFlowGraph.addBlockInstructionConstraints(SimpleDemandPointerFlowGraph.java:476)
	at com.ibm.wala.demandpa.flowgraph.SimpleDemandPointerFlowGraph.addNodeInstructionConstraints(SimpleDemandPointerFlowGraph.java:461)
	at com.ibm.wala.demandpa.flowgraph.SimpleDemandPointerFlowGraph.unconditionallyAddConstraintsFromNode(SimpleDemandPointerFlowGraph.java:383)
	at com.ibm.wala.demandpa.flowgraph.SimpleDemandPointerFlowGraph.addSubgraphForNode(SimpleDemandPointerFlowGraph.java:152)
	at com.ibm.wala.demandpa.flowgraph.SimpleDemandPointerFlowGraph.addParamEdges(SimpleDemandPointerFlowGraph.java:285)
	at com.ibm.wala.demandpa.flowgraph.SimpleDemandPointerFlowGraph.getSuccNodes(SimpleDemandPointerFlowGraph.java:250)
	at com.ibm.wala.util.graph.traverse.GraphDFSDiscoverTimeIterator.getConnected(GraphDFSDiscoverTimeIterator.java:32)
	at com.ibm.wala.util.graph.traverse.DFSDiscoverTimeIterator.init(DFSDiscoverTimeIterator.java:41)
	at com.ibm.wala.util.graph.traverse.GraphDFSDiscoverTimeIterator.init(GraphDFSDiscoverTimeIterator.java:27)
	at com.ibm.wala.util.graph.traverse.SlowDFSDiscoverTimeIterator.<init>(SlowDFSDiscoverTimeIterator.java:39)
	at com.ibm.wala.demandpa.alg.SimpleDemandPointsTo.getPointsTo(SimpleDemandPointsTo.java:99)
	at com.ibm.wala.demandpa.driver.TestAgainstSimpleDriver.runAnalysisForTestCase(TestAgainstSimpleDriver.java:135)
	at com.ibm.wala.demandpa.driver.TestAgainstSimpleDriver.main(TestAgainstSimpleDriver.java:84)
```

**Comment by msridhar** [comment]
Thanks for the report!  I will take a look.
