### ISSUE TITLE
build call graph for some classes

### ISSUE THREAD

**Issue by xxwxxwen** [wala/WALA#1161]
When I build call graph for a jar file,it is a large amount data and takes a lot of time to build. @msridhar How can I only build call graph for some classes in the jar file? Sometimes **set entry point for each class** may fail to build call graph

**Comment by xxwxxwen** [comment]
I still fail to find **test method** in call graph #1160 .When I output all methods in the call graph,it is **not in the call graph**.I still feel a little puzzled.Then,I set entrypoint when build the call graph,not use **AllApplicationEntrypoints**,it occurred the error. @msridhar Do you have any suggestions?

```java
public static CGNode findMethod(CallGraph CG,String methodName, String ClassName){
        if (methodName.equals(null) && ClassName.equals(null))
            return null;
        Atom name = Atom.findOrCreateUnicodeAtom(methodName);
        for (Iterator<? extends CGNode> it = CG.iterator(); it.hasNext();) {
            CGNode n = it.next();
      if(n.getMethod().getDeclaringClass().getName().toString().substring(1).replace('/','.').equals(ClassName)) {
           if(n.getMethod().getName().toString().equals("test")){
                System.out.println(methodName + " " + n.getMethod().getName()+" "+ClassName+" "+n.getMethod().getDeclaringClass().getName());
                return n;
            }
        }
        return null;
    }
Exception in thread "main" java.lang.IllegalStateException: Could not create a entrypoint callsites: 1. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Ljava/applet/Applet$AccessibleApplet> No superclass found for <Primordial,Ljava/applet/Applet$AccessibleApplet> Superclass name Ljava/awt/Panel$AccessibleAWTPanel
2. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Ljava/applet/Applet> No superclass found for <Primordial,Ljava/applet/Applet> Superclass name Ljava/awt/Panel
3. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Ljava/io/FileCleanable> No superclass found for <Primordial,Ljava/io/FileCleanable> Superclass name Ljdk/internal/ref/PhantomCleanable
4. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Ljava/lang/Module$1> No superclass found for <Primordial,Ljava/lang/Module$1> Superclass name Ljdk/internal/org/objectweb/asm/ClassVisitor
5. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Ljava/lang/invoke/InnerClassLambdaMetafactory$ForwardingMethodGenerator> No superclass found for <Primordial,Ljava/lang/invoke/TypeConvertingMethodAdapter> Superclass name Ljdk/internal/org/objectweb/asm/MethodVisitor
6. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Ljava/lang/invoke/TypeConvertingMethodAdapter> No superclass found for <Primordial,Ljava/lang/invoke/TypeConvertingMethodAdapter> Superclass name Ljdk/internal/org/objectweb/asm/MethodVisitor
7. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Ljava/lang/management/DefaultPlatformMBeanProvider> No superclass found for <Primordial,Ljava/lang/management/DefaultPlatformMBeanProvider> Superclass name Lsun/management/spi/PlatformMBeanProvider
8. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Ljava/net/SocketCleanable> No superclass found for <Primordial,Ljava/net/SocketCleanable> Superclass name Ljdk/internal/ref/PhantomCleanable
9. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Ljava/rmi/MarshalledObject$MarshalledObjectInputStream> No superclass found for <Primordial,Ljava/rmi/MarshalledObject$MarshalledObjectInputStream> Superclass name Lsun/rmi/server/MarshalInputStream
10. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Ljava/rmi/MarshalledObject$MarshalledObjectOutputStream> No superclass found for <Primordial,Ljava/rmi/MarshalledObject$MarshalledObjectOutputStream> Superclass name Lsun/rmi/server/MarshalOutputStream
11. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Ljava/rmi/server/RemoteObjectInvocationHandler$MethodToHash_Maps> No superclass found for <Primordial,Ljava/rmi/server/RemoteObjectInvocationHandler$MethodToHash_Maps> Superclass name Lsun/rmi/server/WeakClassHashMap
12. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Ljava/security/cert/CertPathHelperImpl> No superclass found for <Primordial,Ljava/security/cert/CertPathHelperImpl> Superclass name Lsun/security/provider/certpath/CertPathHelper
13. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Ljava/util/Locale$Cache> No superclass found for <Primordial,Ljava/util/Locale$Cache> Superclass name Lsun/util/locale/LocaleObjectCache
14. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Ljava/util/ResourceBundle$Control$CandidateListCache> No superclass found for <Primordial,Ljava/util/ResourceBundle$Control$CandidateListCache> Superclass name Lsun/util/locale/LocaleObjectCache
15. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Ljavax/imageio/metadata/IIODOMException> No superclass found for <Primordial,Ljavax/imageio/metadata/IIODOMException> Superclass name Lorg/w3c/dom/DOMException
16. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Ljavax/management/remote/rmi/RMIConnectionImpl$RMIServerCommunicatorAdmin> No superclass found for <Primordial,Ljavax/management/remote/rmi/RMIConnectionImpl$RMIServerCommunicatorAdmin> Superclass name Lcom/sun/jmx/remote/internal/ServerCommunicatorAdmin
17. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Ljavax/management/remote/rmi/RMIConnector$RMIClientCommunicatorAdmin> No superclass found for <Primordial,Ljavax/management/remote/rmi/RMIConnector$RMIClientCommunicatorAdmin> Superclass name Lcom/sun/jmx/remote/internal/ClientCommunicatorAdmin
18. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Ljavax/management/remote/rmi/RMIConnector$RMINotifClient> No superclass found for <Primordial,Ljavax/management/remote/rmi/RMIConnector$RMINotifClient> Superclass name Lcom/sun/jmx/remote/internal/ClientNotifForwarder
19. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Ljavax/print/attribute/standard/DialogOwner$Accessor> No superclass found for <Primordial,Ljavax/print/attribute/standard/DialogOwner$Accessor> Superclass name Lsun/print/DialogOwnerAccessor
20. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/code/SourceStackTraceBailoutException$1> No superclass found for <Primordial,Lorg/graalvm/compiler/core/common/GraalBailoutException> Superclass name Ljdk/vm/ci/code/BailoutException
21. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/code/SourceStackTraceBailoutException> No superclass found for <Primordial,Lorg/graalvm/compiler/core/common/GraalBailoutException> Superclass name Ljdk/vm/ci/code/BailoutException
22. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/core/common/CancellationBailoutException> No superclass found for <Primordial,Lorg/graalvm/compiler/core/common/GraalBailoutException> Superclass name Ljdk/vm/ci/code/BailoutException
23. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/core/common/GraalBailoutException> No superclass found for <Primordial,Lorg/graalvm/compiler/core/common/GraalBailoutException> Superclass name Ljdk/vm/ci/code/BailoutException
24. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/core/common/LIRKind> No superclass found for <Primordial,Lorg/graalvm/compiler/core/common/LIRKind> Superclass name Ljdk/vm/ci/meta/ValueKind
25. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/core/common/PermanentBailoutException> No superclass found for <Primordial,Lorg/graalvm/compiler/core/common/GraalBailoutException> Superclass name Ljdk/vm/ci/code/BailoutException
26. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/core/common/RetryableBailoutException> No superclass found for <Primordial,Lorg/graalvm/compiler/core/common/GraalBailoutException> Superclass name Ljdk/vm/ci/code/BailoutException
27. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/core/match/ComplexMatchValue$1> No superclass found for <Primordial,Lorg/graalvm/compiler/core/match/ComplexMatchValue$1> Superclass name Ljdk/vm/ci/meta/Value
28. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/core/match/ComplexMatchValue> No superclass found for <Primordial,Lorg/graalvm/compiler/core/match/ComplexMatchValue> Superclass name Ljdk/vm/ci/meta/Value
29. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/graph/Graph$1> No superclass found for <Primordial,Lorg/graalvm/compiler/graph/Graph$1> Superclass name Ljdk/internal/vm/compiler/collections/Equivalence
30. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/graph/InlineCacheGuardPosition> No superclass found for <Primordial,Lorg/graalvm/compiler/graph/NodeSourcePosition> Superclass name Ljdk/vm/ci/code/BytecodePosition
31. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/graph/NodeSourcePosition> No superclass found for <Primordial,Lorg/graalvm/compiler/graph/NodeSourcePosition> Superclass name Ljdk/vm/ci/code/BytecodePosition
32. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/hotspot/AOTGraalHotSpotVMConfig> No superclass found for <Primordial,Lorg/graalvm/compiler/hotspot/GraalHotSpotVMConfigBase> Superclass name Ljdk/vm/ci/hotspot/HotSpotVMConfigAccess
33. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/hotspot/CompilerRuntimeHotSpotVMConfig> No superclass found for <Primordial,Lorg/graalvm/compiler/hotspot/CompilerRuntimeHotSpotVMConfig> Superclass name Ljdk/vm/ci/hotspot/HotSpotVMConfigAccess
34. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/hotspot/GraalHotSpotVMConfig> No superclass found for <Primordial,Lorg/graalvm/compiler/hotspot/GraalHotSpotVMConfigBase> Superclass name Ljdk/vm/ci/hotspot/HotSpotVMConfigAccess
35. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/hotspot/GraalHotSpotVMConfigBase> No superclass found for <Primordial,Lorg/graalvm/compiler/hotspot/GraalHotSpotVMConfigBase> Superclass name Ljdk/vm/ci/hotspot/HotSpotVMConfigAccess
36. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/hotspot/GraalHotSpotVMConfigVersioned> No superclass found for <Primordial,Lorg/graalvm/compiler/hotspot/GraalHotSpotVMConfigVersioned> Superclass name Ljdk/vm/ci/hotspot/HotSpotVMConfigAccess
37. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/hotspot/HotSpotForeignCallLinkageImpl> No superclass found for <Primordial,Lorg/graalvm/compiler/hotspot/HotSpotForeignCallLinkageImpl> Superclass name Ljdk/vm/ci/hotspot/HotSpotForeignCallTarget
38. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/hotspot/HotSpotGraalCompilerFactory> No superclass found for <Primordial,Lorg/graalvm/compiler/hotspot/HotSpotGraalCompilerFactory> Superclass name Ljdk/vm/ci/hotspot/HotSpotJVMCICompilerFactory
39. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/hotspot/HotSpotGraalJVMCIServiceLocator> No superclass found for <Primordial,Lorg/graalvm/compiler/hotspot/HotSpotGraalJVMCIServiceLocator> Superclass name Ljdk/vm/ci/services/JVMCIServiceLocator
40. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/hotspot/WeakClassLoaderSet$RefEquivalence> No superclass found for <Primordial,Lorg/graalvm/compiler/hotspot/WeakClassLoaderSet$RefEquivalence> Superclass name Ljdk/internal/vm/compiler/collections/Equivalence
41. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/hotspot/replacements/HotSpotReplacementsUtil$1> No superclass found for <Primordial,Lorg/graalvm/compiler/nodes/NamedLocationIdentity> Superclass name Ljdk/internal/vm/compiler/word/LocationIdentity
42. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/hotspot/replacements/HotSpotReplacementsUtil$2> No superclass found for <Primordial,Lorg/graalvm/compiler/nodes/NamedLocationIdentity> Superclass name Ljdk/internal/vm/compiler/word/LocationIdentity
43. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/hotspot/replacements/HotSpotReplacementsUtil$3> No superclass found for <Primordial,Lorg/graalvm/compiler/nodes/NamedLocationIdentity> Superclass name Ljdk/internal/vm/compiler/word/LocationIdentity
44. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/hotspot/replacements/HotSpotReplacementsUtil$4> No superclass found for <Primordial,Lorg/graalvm/compiler/nodes/NamedLocationIdentity> Superclass name Ljdk/internal/vm/compiler/word/LocationIdentity
45. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/hotspot/replacements/HotSpotReplacementsUtil$5> No superclass found for <Primordial,Lorg/graalvm/compiler/nodes/NamedLocationIdentity> Superclass name Ljdk/internal/vm/compiler/word/LocationIdentity
46. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/hotspot/replacements/HotSpotReplacementsUtil$6> No superclass found for <Primordial,Lorg/graalvm/compiler/nodes/NamedLocationIdentity> Superclass name Ljdk/internal/vm/compiler/word/LocationIdentity
47. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/hotspot/replacements/HotSpotReplacementsUtil$HotSpotOptimizingLocationIdentity> No superclass found for <Primordial,Lorg/graalvm/compiler/nodes/NamedLocationIdentity> Superclass name Ljdk/internal/vm/compiler/word/LocationIdentity
48. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/java/JsrNotSupportedBailout> No superclass found for <Primordial,Lorg/graalvm/compiler/core/common/GraalBailoutException> Superclass name Ljdk/vm/ci/code/BailoutException
49. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/lir/BailoutAndRestartBackendException> No superclass found for <Primordial,Lorg/graalvm/compiler/core/common/GraalBailoutException> Superclass name Ljdk/vm/ci/code/BailoutException
50. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/lir/CompositeValue> No superclass found for <Primordial,Lorg/graalvm/compiler/lir/CompositeValue> Superclass name Ljdk/vm/ci/meta/Value
51. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/lir/ConstantValue> No superclass found for <Primordial,Lorg/graalvm/compiler/lir/ConstantValue> Superclass name Ljdk/vm/ci/meta/Value
52. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/lir/Variable> No superclass found for <Primordial,Lorg/graalvm/compiler/lir/Variable> Superclass name Ljdk/vm/ci/meta/AllocatableValue
53. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/lir/VirtualStackSlot> No superclass found for <Primordial,Lorg/graalvm/compiler/lir/VirtualStackSlot> Superclass name Ljdk/vm/ci/meta/AllocatableValue
54. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/lir/aarch64/AArch64AddressValue> No superclass found for <Primordial,Lorg/graalvm/compiler/lir/CompositeValue> Superclass name Ljdk/vm/ci/meta/Value
55. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/lir/alloc/OutOfRegistersException> No superclass found for <Primordial,Lorg/graalvm/compiler/core/common/GraalBailoutException> Superclass name Ljdk/vm/ci/code/BailoutException
56. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/lir/amd64/AMD64AddressValue> No superclass found for <Primordial,Lorg/graalvm/compiler/lir/CompositeValue> Superclass name Ljdk/vm/ci/meta/Value
57. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/lir/framemap/SimpleVirtualStackSlot> No superclass found for <Primordial,Lorg/graalvm/compiler/lir/VirtualStackSlot> Superclass name Ljdk/vm/ci/meta/AllocatableValue
58. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/lir/framemap/VirtualStackSlotRange> No superclass found for <Primordial,Lorg/graalvm/compiler/lir/VirtualStackSlot> Superclass name Ljdk/vm/ci/meta/AllocatableValue
59. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/lir/sparc/SPARCAddressValue> No superclass found for <Primordial,Lorg/graalvm/compiler/lir/CompositeValue> Superclass name Ljdk/vm/ci/meta/Value
60. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/lir/sparc/SPARCImmediateAddressValue> No superclass found for <Primordial,Lorg/graalvm/compiler/lir/CompositeValue> Superclass name Ljdk/vm/ci/meta/Value
61. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/lir/sparc/SPARCIndexedAddressValue> No superclass found for <Primordial,Lorg/graalvm/compiler/lir/CompositeValue> Superclass name Ljdk/vm/ci/meta/Value
62. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/nodes/FieldLocationIdentity> No superclass found for <Primordial,Lorg/graalvm/compiler/nodes/FieldLocationIdentity> Superclass name Ljdk/internal/vm/compiler/word/LocationIdentity
63. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/nodes/NamedLocationIdentity> No superclass found for <Primordial,Lorg/graalvm/compiler/nodes/NamedLocationIdentity> Superclass name Ljdk/internal/vm/compiler/word/LocationIdentity
64. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Lorg/graalvm/compiler/word/Word$BoxFactoryImpl> No superclass found for <Primordial,Lorg/graalvm/compiler/word/Word$BoxFactoryImpl> Superclass name Ljdk/internal/vm/compiler/word/impl/WordBoxFactory
65. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Ljdk/internal/access/JavaBeansAccess
66. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Ljdk/internal/access/JavaIOAccess
67. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Ljdk/internal/access/JavaIOFileDescriptorAccess
68. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Ljdk/internal/access/JavaIOFilePermissionAccess
69. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Ljdk/internal/access/JavaIORandomAccessFileAccess
70. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Ljdk/internal/access/JavaLangAccess
71. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Ljdk/internal/access/JavaLangInvokeAccess
72. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Ljdk/internal/access/JavaLangModuleAccess
73. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Ljdk/internal/access/JavaLangRefAccess
74. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Ljdk/internal/access/JavaNetHttpCookieAccess
75. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Ljdk/internal/access/JavaNetInetAddressAccess
76. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Ljdk/internal/access/JavaNetSocketAccess
77. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Ljdk/internal/access/JavaNetURLAccess
78. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Ljdk/internal/access/JavaNetURLClassLoaderAccess
79. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Ljdk/internal/access/JavaNetUriAccess
80. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Ljdk/internal/access/JavaNioAccess
81. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Ljdk/internal/access/JavaNioAccess$BufferPool
82. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Ljdk/internal/access/JavaSecurityAccess
83. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Ljdk/internal/access/JavaSecurityAccess$ProtectionDomainCache
84. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Ljdk/internal/access/JavaUtilJarAccess
85. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Ljdk/internal/access/JavaUtilResourceBundleAccess
86. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Ljdk/internal/access/JavaUtilZipFileAccess
87. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Ljdk/internal/misc/Signal$Handler
88. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Ljdk/internal/reflect/LangReflectAccess
89. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Ljdk/internal/vm/compiler/collections/EconomicMap
90. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Ljdk/internal/vm/compiler/collections/MapCursor
91. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Ljdk/internal/vm/compiler/word/Pointer
92. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Ljdk/internal/vm/compiler/word/SignedWord
93. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Ljdk/internal/vm/compiler/word/UnsignedWord
94. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Ljdk/vm/ci/code/ValueKindFactory
95. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Ljdk/vm/ci/hotspot/HotSpotVMEventListener
96. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Ljdk/vm/ci/meta/ConstantPool
97. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Ljdk/vm/ci/meta/InvokeTarget
98. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Ljdk/vm/ci/meta/JavaMethod
99. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Ljdk/vm/ci/meta/JavaType
100. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Ljdk/vm/ci/meta/SerializableConstant
101. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Ljdk/vm/ci/meta/SpeculationLog$SpeculationReason
102. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Ljdk/vm/ci/runtime/JVMCICompiler
103. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Lorg/w3c/dom/Attr
104. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Lorg/w3c/dom/Element
105. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Lorg/w3c/dom/NamedNodeMap
106. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Lorg/w3c/dom/NodeList
107. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Lorg/w3c/dom/ls/LSInput
108. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Lorg/w3c/dom/ls/LSResourceResolver
109. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Lsun/awt/AWTAccessor$AccessibleBundleAccessor
110. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Lsun/awt/AWTAccessor$AccessibleContextAccessor
111. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Lsun/java2d/DisposerRecord
112. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Lsun/management/spi/PlatformMBeanProvider$PlatformComponent
113. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Lsun/nio/ch/DirectBuffer
114. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Lsun/nio/ch/Interruptible
115. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Lsun/security/krb5/JavaxSecurityAuthKerberosAccess
116. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Lsun/security/util/MessageDigestSpi2
117. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Lsun/util/locale/provider/LocaleServiceProviderPool$LocalizedObjectGetter
118. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Lsun/util/logging/internal/LoggingProviderImpl$LogManagerAccess
119. [SEVERE] class com.ibm.wala.ipa.callgraph.impl.AbstractRootMethod$AllocationFailure : <Application,Lorg/apache/bcel/classfile/JavaClass>
120. [SEVERE] class com.ibm.wala.ipa.callgraph.propagation.PropagationCallGraphBuilder$EntrypointResolutionWarning : < Application, Ledu/berkeley/cs/jqf/examples/bcel/ParserTest, testWithGenerator(Lorg/apache/bcel/classfile/JavaClass;)V >([<Application,Ledu/berkeley/cs/jqf/examples/bcel/ParserTest>],[<Application,Lorg/apache/bcel/classfile/JavaClass>])

	at com.ibm.wala.ipa.callgraph.propagation.PropagationCallGraphBuilder.makeCallGraph(PropagationCallGraphBuilder.java:241)
	at top.anemone.walaDemo.WalaTest5.main(WalaTest5.java:99)

**Comment by msridhar** [comment]
> When I build call graph for a jar file,it is a large amount data and takes a lot of time to build. @msridhar How can I only build call graph for some classes in the jar file? Sometimes **set entry point for each class** may fail to build call graph

I think what you want to use is an exclusions file:

https://github.com/wala/WALA/wiki/Analysis-Scope#exclusions-files

> I still fail to find **test method** in call graph #1160 .When I output all methods in the call graph,it is **not in the call graph**.I still feel a little puzzled.

I'm not sure what is going on.  If you create a self-contained example and also post your code that uses WALA I can try to see what is going on.
