### ISSUE TITLE
Configuration cache fails for the `compileTestJava` task

### ISSUE THREAD

**Issue by msridhar** [wala/WALA#1230]
I tried running `./gradlew --configuration-cache compileTestJava`, which I expected to succeed.  Instead, I got a failure:
```
* What went wrong:
Configuration cache problems found in this build.

1 problem was found storing the configuration cache.
- Build file 'build.gradle.kts': external process started 'uname -a'
  See https://docs.gradle.org/7.6/userguide/configuration_cache.html#config_cache:requirements:external_processes
```

In the report file, here is some of the failure stack:
```
org.gradle.api.InvalidUserCodeException: Starting an external process 'uname -a' during configuration time is unsupported.
	at org.gradle.configurationcache.initialization.DefaultConfigurationCacheProblemsListener.onExternalProcessStarted(ConfigurationCacheProblemsListener.kt:84)
	at org.gradle.configurationcache.InstrumentedInputAccessListener.externalProcessStarted(InstrumentedInputAccessListener.kt:110)
	at org.gradle.internal.classpath.Instrumented.externalProcessStarted(Instrumented.java:394)
	at org.gradle.internal.classpath.Instrumented.externalProcessStarted(Instrumented.java:398)
	at org.gradle.internal.classpath.Instrumented.exec(Instrumented.java:259)
	at com.diffplug.common.swt.os.OS.exec(OS.java:156)
	at com.diffplug.common.swt.os.OS.calculateNative(OS.java:133)
	at com.diffplug.common.swt.os.OS.detectPlatform(OS.java:113)
	at com.diffplug.common.swt.os.OS.detectPlatform(OS.java:120)
	at com.diffplug.common.swt.os.OS.getNative(OS.java:100)
	at com.diffplug.gradle.FileMisc.<clinit>(FileMisc.java:426)
	at com.diffplug.gradle.eclipse.MavenCentralMapping.createVersionMap(MavenCentralMapping.java:138)
	at com.diffplug.gradle.eclipse.MavenCentralMapping.groupIdArtifactIdToVersion(MavenCentralMapping.java:124)
	at com.diffplug.gradle.eclipse.MavenCentralExtension$ReleaseConfigurer.<init>(MavenCentralExtension.java:56)
	at com.diffplug.gradle.eclipse.MavenCentralExtension.release(MavenCentralExtension.java:47)
	at com.diffplug.gradle.eclipse.MavenCentralExtension.release(MavenCentralExtension.java:43)
```

This is on my Mac with Java 11.  It looks like it may be an issue in the `com.diffplug.eclipse.mavencentral` plugin.  Just FYI @liblit, if you have time to take a look, maybe we can get another upstream issue fixed :-)

**Comment by liblit** [comment]
I am unable to reproduce this problem on Linux. That clue, plus the "`com.diffplug.common.swt.os.OS.calculateNative(OS.java:133)`" line from the stack trace, lead me to [this macOS-specific code](https://github.com/diffplug/durian-swt/blob/385d94a79949dff5ce4f76c46f10256da9aedd84/durian-swt.os/src/main/java/com/diffplug/common/swt/os/OS.java#L132-L133):

```java
if (isMac) {
	return exec("uname", "-a").contains("_ARM64_") ? MAC_silicon : MAC_x64;
```

So yes, as @msridhar suspected, this will require a fix in a third-party Gradle plugin that we use: `com.diffplug.eclipse.mavencentral`, for which we are already using the latest 3.40.0 release. I'll submit a bug report for that plugin.

**Comment by msridhar** [comment]
Awesome, thanks!

**Comment by liblit** [comment]
Reported upstream as diffplug/goomph#203.
