### ISSUE TITLE
Exception when making a ClassHierarchy from an Eclipse project

### ISSUE THREAD

**Issue by khatchad** [wala/WALA#131]
I am trying to create a `ClassHierarchy` from an `IJavaProject` within an Eclipse plugin. However, I am receiving an `IllegalArgumentException` when doing so.

Here's a snippet of my code:
```java
class MyVisitor extends ASTVisitor {
    @Override
    public boolean visit(MethodInvocation node) {
        IMethodBinding methodBinding = node.resolveMethodBinding();
        IJavaElement javaElement = methodBinding.getJavaElement();
	IJavaProject javaProject = javaElement.getJavaProject();
        JavaEclipseProjectPath path = JavaEclipseProjectPath.make(javaProject, AnalysisScopeType.SOURCE_FOR_PROJ_AND_LINKED_PROJS);
        AnalysisScope scope = path.toAnalysisScope();
        ClassHierarchy cha = ClassHierarchy.make(scope); // Exception happens HERE.
        // ...
    }
}
```
Here's the exception I get:
```java
java.lang.IllegalArgumentException: class <Extension,Ljava/lang/Object> is invalid, unexpected classloader
	at com.ibm.wala.ipa.cha.ClassHierarchy.addClass(ClassHierarchy.java:303)
	at com.ibm.wala.ipa.cha.ClassHierarchy.addAllClasses(ClassHierarchy.java:283)
	at com.ibm.wala.ipa.cha.ClassHierarchy.<init>(ClassHierarchy.java:244)
	at com.ibm.wala.ipa.cha.ClassHierarchy.<init>(ClassHierarchy.java:177)
	at com.ibm.wala.ipa.cha.ClassHierarchy.make(ClassHierarchy.java:1230)
	at com.ibm.wala.ipa.cha.ClassHierarchy.make(ClassHierarchy.java:1210)
```

I know that the class loading model differs for Eclipse projects. Is there something I need to do prior to creating the `ClassHierarchy`?

**Comment by khatchad** [comment]
I think the problem may have something to do with *how* I am running the code. If I run the plugin in a user environment (i.e., in a normal Eclipse instance), I do not get the exception. However, I originally ran this code as an Eclipse Plug-in Test, in which case the error does occur.

Diving further into this, this is what my `EclipseProjectPath` looks like (as show by `toString()`, note that I changed the `AnalysisScopeType` to `NO_SOURCE`) when I run it as a normal Eclipse application (and do *not* get the exception):

```
Primordial
 Jar input stream com.ibm.wala.classLoader.JarStreamModule@64d621ae
 JarFileModule:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/resources.jar
 JarFileModule:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar
 JarFileModule:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jsse.jar
 JarFileModule:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jce.jar
 JarFileModule:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/charsets.jar
 JarFileModule:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/icedtea-sound.jar
 JarFileModule:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/cldrdata.jar
 JarFileModule:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/zipfs.jar
 JarFileModule:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunjce_provider.jar
 JarFileModule:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/nashorn.jar
 JarFileModule:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunec.jar
 JarFileModule:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/dnsns.jar
 JarFileModule:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/localedata.jar
 JarFileModule:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/jaccess.jar
 JarFileModule:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunpkcs11.jar
Extension
Application
 com.ibm.wala.classLoader.BinaryDirectoryTreeModule:/home/rk1424/Workspaces/runtime-EclipseApplication/Test/bin
Synthetic
Exclusions: null
```
This looks reasonable as library code is loaded into Primordial.

On the other hand, when I run as a plug-in test, it looks like this:
```
Primordial
 Jar input stream com.ibm.wala.classLoader.JarStreamModule@2eace5db
Extension
 JarFileModule:/Users/raffi/.p2/pool/plugins/org.eclipse.jdt.ui.tests_3.12.2.v20160929-1056/testresources/rtstubs18.jar
Application
 com.ibm.wala.classLoader.BinaryDirectoryTreeModule:/home/rk1424/Workspaces/junit-workspace/TestProject1484263233394/bin
Synthetic
Exclusions: null
```
I would think that `rtstubs18.jar` should be in Primordinal rather than Extension.

**Comment by khatchad** [comment]
Looks like part of the problem may be that `com.ibm.wala.ide.util.EclipseProjectPath.isPrimordialJarFile(JarFile)` is really not being used. Indeed, `rtstubs18.jar` should cause this method to return true, but it currently always returns true. Moreover, when it return true, `com.ibm.wala.ide.util.EclipseProjectPath.resolveLibraryPathEntry(ILoader, IPath)` will add the jar to the *given* loader instead of forcing primordial.

**Comment by msridhar** [comment]
@juliandolby any ideas here?  I am not super familiar with this code.

**Comment by khatchad** [comment]
Please let me know if you need more information here as well for this issue.
