### ISSUE TITLE
A crash bug about points-to analysis in ZeroCFA

### ISSUE THREAD

**Issue by donaldTech123** [wala/WALA#1356]
Hi, I use the following Wala configuration code to analyze a class file. However, Wala has a runtime crash bug. The Wala version is: 1.6.2, and I use maven to integrate it.

#### Wala Code
```java
AnalysisScope scope = AnalysisScopeReader.instance.makeJavaBinaryAnalysisScope(inputFile, walaExclusionFile);
IClassHierarchy cha = ClassHierarchyFactory.make(scope);
Iterable<Entrypoint> entryPoints = Util.makeMainEntrypoints(cha);
AnalysisOptions options = new AnalysisOptions(scope, entryPoints);
AnalysisCache cache = new AnalysisCacheImpl();
CallGraphBuilder<InstanceKey> builder = Util.makeZeroCFABuilder(Language.JAVA, options, cache, cha);
CallGraph cg = builder.makeCallGraph(options, null);
PointerAnalysis<InstanceKey> pointerAnalysis = builder.getPointerAnalysis();
for (PointerKey pk : pointerAnalysis.getPointerKeys()) {
    if (pk instanceof LocalPointerKey lpk) {
        String className = lpk.getNode().getMethod().getDeclaringClass().getName().toString();
        String methodName = lpk.getNode().getMethod().getName().toString();
        ClassLoaderReference clr = lpk.getNode().getMethod().getDeclaringClass().getClassLoader().getReference();
        if (clr.equals(ClassLoaderReference.Application) && className.equals("LExample") && methodName.equals("foo")) {
            if (lpk.isParameter()) {
                for (InstanceKey ik : pointerAnalysis.getPointsToSet(lpk)) {
                    Iterator<Pair<CGNode, NewSiteReference>> iterator = ik.getCreationSites(cg);
                    while (iterator.hasNext()) {
                        iterator.next();  // crash here
                    }
                }
            }
        }
    }
}
```

#### Minimized Source Code Example
```java
public class Example {
  private static int i = 0;
  public static void main(String[] args) {
      Object obj1 = new Object();
      Object obj2 = "1";
      Object obj3 = 1;
      if (i == 0) {
          obj1 = obj3;
      } else if (i == 1) {
          obj2 = obj3;
      }
      foo(obj1, obj2);
  }
  private static void foo(Object o1, Object o2) {}
}
```

#### Stack trace of the crash
```bash
java.lang.ClassCastException: class com.ibm.wala.ipa.callgraph.DelegatingContext cannot be cast to class com.ibm.wala.analysis.reflection.GetMethodContext (com.ibm.wala.ipa.callgraph.DelegatingContext and com.ibm.wala.analysis.reflection.GetMethodContext are in unnamed module of loader 'app')
	at com.ibm.wala.analysis.reflection.GetMethodContextInterpreter.iterateNewSites(GetMethodContextInterpreter.java:140)
	at com.ibm.wala.ipa.callgraph.propagation.rta.DelegatingRTAContextInterpreter.iterateNewSites(DelegatingRTAContextInterpreter.java:48)
	at com.ibm.wala.ipa.callgraph.propagation.rta.DelegatingRTAContextInterpreter.iterateNewSites(DelegatingRTAContextInterpreter.java:48)
	at com.ibm.wala.ipa.callgraph.impl.ExplicitCallGraph$ExplicitNode.iterateNewSites(ExplicitCallGraph.java:321)
	at com.ibm.wala.ipa.callgraph.propagation.ConcreteTypeKey$1.makeInner(ConcreteTypeKey.java:103)
	at com.ibm.wala.ipa.callgraph.propagation.ConcreteTypeKey$1.makeInner(ConcreteTypeKey.java:98)
	at com.ibm.wala.util.collections.ComposedIterator.advanceOuter(ComposedIterator.java:30)
	at com.ibm.wala.util.collections.ComposedIterator.next(ComposedIterator.java:57)
```

Notice that, when I change 0-CFA to RTA, the program can execute properly.

**Comment by msridhar** [comment]
Thanks for the report @donaldTech123.  I will try to take a look when I get a bit of time.
