### ISSUE TITLE
java.lang.Error: unexpected dynamic invoke type 8

### ISSUE THREAD

**Issue by khatchad** [wala/WALA#137]
I am receiving an `java.lang.Error: unexpected dynamic invoke type 8` error when building a call graph of the following program:

```java
package p;

import java.util.HashSet;
import java.util.Set;
import java.util.stream.Stream;

class A {
	void m() {
		Set<Object> set = new HashSet<>();
		Stream<Object> stream = set.parallelStream();
		stream.sorted(); // this call forces the error.
	}
}
```
I am on 137fed6e625ca69218a4277aa0171eee94f91cf8.

Error details:
```
java.lang.Error: unexpected dynamic invoke type 8
	at com.ibm.wala.ipa.summaries.LambdaSummaryClass.makeTrampoline(LambdaSummaryClass.java:267)
	at com.ibm.wala.ipa.summaries.LambdaSummaryClass.<init>(LambdaSummaryClass.java:70)
	at com.ibm.wala.ipa.summaries.LambdaSummaryClass.findOrCreate(LambdaSummaryClass.java:52)
	at com.ibm.wala.ipa.summaries.LambdaMethodTargetSelector.getCalleeTarget(LambdaMethodTargetSelector.java:65)
	at com.ibm.wala.ipa.summaries.BypassMethodTargetSelector.getCalleeTarget(BypassMethodTargetSelector.java:136)
	at com.ibm.wala.ipa.callgraph.propagation.PropagationCallGraphBuilder.getTargetForCall(PropagationCallGraphBuilder.java:716)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$1.apply(SSAPropagationCallGraphBuilder.java:2029)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$1.apply(SSAPropagationCallGraphBuilder.java:1)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$CrossProductRec.rec(SSAPropagationCallGraphBuilder.java:532)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.iterateCrossProduct(SSAPropagationCallGraphBuilder.java:2009)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.getTargetsForCall(SSAPropagationCallGraphBuilder.java:2035)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$ConstraintVisitor.visitInvokeInternal(SSAPropagationCallGraphBuilder.java:1141)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$ConstraintVisitor.visitInvoke(SSAPropagationCallGraphBuilder.java:1111)
	at com.ibm.wala.ssa.SSAInvokeInstruction.visit(SSAInvokeInstruction.java:87)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.addBlockInstructionConstraints(SSAPropagationCallGraphBuilder.java:291)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.addNodeInstructionConstraints(SSAPropagationCallGraphBuilder.java:262)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.unconditionallyAddConstraintsFromNode(SSAPropagationCallGraphBuilder.java:233)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.addConstraintsFromNode(SSAPropagationCallGraphBuilder.java:199)
	at com.ibm.wala.ipa.callgraph.propagation.PropagationCallGraphBuilder.addConstraintsFromNewNodes(PropagationCallGraphBuilder.java:337)
	at com.ibm.wala.ipa.callgraph.propagation.StandardSolver.solve(StandardSolver.java:58)
	at com.ibm.wala.ipa.callgraph.propagation.PropagationCallGraphBuilder.makeCallGraph(PropagationCallGraphBuilder.java:270)
	at com.ibm.wala.client.AbstractAnalysisEngine.buildCallGraph(AbstractAnalysisEngine.java:140)
...
```

**Comment by juliandolby** [comment]
While I did implement invokeDynamic support, it seems that I neglected 1 of the 5 cases in one place, perhaps because I had not seen it in Java 7.  I believe I have checked in a fix, along with a new test that uses the feature that generates dynamic invoke type 8.

**Comment by juliandolby** [comment]
I believe I have fixed this.  I have checked in a test that creates a dynamic invoke type 8, and ensures we can build a call graph for it.

**Comment by khatchad** [comment]
Looks like the fix is in up to 017a715cd5094b15badb09df6efe62c43c022133.

**Comment by khatchad** [comment]
Both 7b393a7da25b3718994a616bb063b9f2665a66e9 and 017a715cd5094b15badb09df6efe62c43c022133 seem to be the complete change set for this issue.

**Comment by juliandolby** [comment]
Indeed, this should have been fixed.  Look at LambdaTest.testStreamExample_137, which analyzes byte code containing that invoke type.

**Comment by khatchad** [comment]
Thanks, @juliandolby. My own test is failing when I integrate this change but I want to localize it and ensure that this change set is the cause and not other changes that were introduced since the last time I pulled from origin/master.

**Comment by khatchad** [comment]
OK, the example I gave above seems to work fine now. However, there is another example that was giving me the same error. With the fix (and using this new example), I am now receiving a different error.

Here's the new example:
```java
package p;

import java.util.HashSet;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;

class A {
	void m() {
		Set<Object> set = new HashSet<>();
		Stream<Object> stream = set.parallelStream();
		stream.sorted(); 
		stream.collect(Collectors.toList()); // this call forces the error.
	}
}
```
And the error I am receiving:
```java
------------------ ERROR:
LocalPointerKey: [Node: synthetic < Primordial, Lwala/lambda$java$util$stream$Nodes$CollectorTask$OfRef$1, apply(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; > Context: CallStringContext: [ java.util.stream.Nodes$CollectorTask.onCompletion(Ljava/util/concurrent/CountedCompleter;)V@32 java.util.concurrent.CountedCompleter.tryComplete()V@15 ], v2]
Constant? false
   -- IR:
synthetic < Primordial, Lwala/lambda$java$util$stream$Nodes$CollectorTask$OfRef$1, apply(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; >
CFG:
BB0[0..0]
    -> BB1
    -> BB3
BB1[1..1]
    -> BB2
    -> BB3
BB2[2..2]
    -> BB3
BB3[-1..-2]
Instructions:
BB0
0   v2 = new <Application,Ljava/util/stream/Nodes$ConcNode>@1
BB1
1   invokespecial < Application, Ljava/util/stream/Nodes$ConcNode, <init>(Ljava/util/stream/Node;Ljava/util/stream/Node;)V > v2,v3,v4 @2 exception:v3
BB2
2   return v2                                
BB3


!ENTRY org.eclipse.core.jobs 4 2 2017-03-13 17:04:29.135
!MESSAGE An internal error occurred during: "...".
!STACK 0
com.ibm.wala.util.debug.UnimplementedError: How can parameter be implicit?
	at com.ibm.wala.util.debug.Assertions.UNREACHABLE(Assertions.java:55)
	at com.ibm.wala.ipa.callgraph.propagation.PropagationSystem.recordImplicitPointsToSet(PropagationSystem.java:246)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$ConstraintVisitor.visitNew(SSAPropagationCallGraphBuilder.java:1222)
	at com.ibm.wala.ssa.SSANewInstruction.visit(SSANewInstruction.java:101)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.addBlockInstructionConstraints(SSAPropagationCallGraphBuilder.java:292)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.addNodeInstructionConstraints(SSAPropagationCallGraphBuilder.java:263)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.unconditionallyAddConstraintsFromNode(SSAPropagationCallGraphBuilder.java:235)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.addConstraintsFromNode(SSAPropagationCallGraphBuilder.java:201)
	at com.ibm.wala.ipa.callgraph.propagation.PropagationCallGraphBuilder.addConstraintsFromNewNodes(PropagationCallGraphBuilder.java:338)
	at com.ibm.wala.ipa.callgraph.propagation.StandardSolver.solve(StandardSolver.java:58)
	at com.ibm.wala.ipa.callgraph.propagation.PropagationCallGraphBuilder.makeCallGraph(PropagationCallGraphBuilder.java:271)
	at com.ibm.wala.client.AbstractAnalysisEngine.buildCallGraph(AbstractAnalysisEngine.java:142)
...
```
I am at bb0f38338e00a9ffb37b711a08db10ea8a4dc332.

**Comment by khatchad** [comment]
I filed https://github.com/wala/WALA/issues/144 since it seems to be a different issue, i.e., the issue originally report looks fixed (but perhaps was masking this new one).
