### ISSUE TITLE
`com.ibm.wala.core.util.ref.ReferenceCleanser.clearSoftCaches()` throws `java.util.ConcurrentModificationException`

### ISSUE THREAD

**Issue by khatchad** [wala/WALA#1377]
From time to time, I am seeing the [below failure](https://github.com/ponder-lab/ML/actions/runs/8330346871/job/22794768580#step:11:32490):

```
java.util.ConcurrentModificationException
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.base/java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:746)
	at com.ibm.wala.util.collections.MapIterator.next(MapIterator.java:34)
	at com.ibm.wala.core.util.ref.ReferenceCleanser.clearSoftCaches(ReferenceCleanser.java:77)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.unconditionallyAddConstraintsFromNode(SSAPropagationCallGraphBuilder.java:202)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.addConstraintsFromNode(SSAPropagationCallGraphBuilder.java:191)
	at com.ibm.wala.ipa.callgraph.propagation.PropagationCallGraphBuilder.addConstraintsFromNewNodes(PropagationCallGraphBuilder.java:308)
	at com.ibm.wala.ipa.callgraph.propagation.StandardSolver.solve(StandardSolver.java:53)
	at com.ibm.wala.ipa.callgraph.propagation.PropagationCallGraphBuilder.makeCallGraph(PropagationCallGraphBuilder.java:248)
	at com.ibm.wala.ipa.callgraph.propagation.PropagationCallGraphBuilder.makeCallGraph(PropagationCallGraphBuilder.java:191)
	at com.ibm.wala.cast.python.ml.test.TestTensorflow2Model.test(TestTensorflow2Model.java:1504)
	at com.ibm.wala.cast.python.ml.test.TestTensorflow2Model.testDataset31(TestTensorflow2Model.java:1059)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:398)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

I believe the iteration causing the problem is happening here:

https://github.com/wala/WALA/blob/45fa20ff0d31d72ff1c363ee153511a57da1b40e/core/src/main/java/com/ibm/wala/core/util/ref/ReferenceCleanser.java#L77

The involved `IClassHierarchy` is coming from here:

https://github.com/wala/WALA/blob/45fa20ff0d31d72ff1c363ee153511a57da1b40e/core/src/main/java/com/ibm/wala/core/util/ref/ReferenceCleanser.java#L75C5-L75C20

Which is coming from here:

https://github.com/wala/WALA/blob/45fa20ff0d31d72ff1c363ee153511a57da1b40e/core/src/main/java/com/ibm/wala/core/util/ref/ReferenceCleanser.java#L40-L46

The corresponding (static) field is here:

https://github.com/wala/WALA/blob/45fa20ff0d31d72ff1c363ee153511a57da1b40e/core/src/main/java/com/ibm/wala/core/util/ref/ReferenceCleanser.java#L32

Perhaps there needs to be some synchronization around this (static) field?

**Comment by msridhar** [comment]
Hi @khatchad it's not clear to me this is an issue with multithreading. Do you have evidence of that? Like is this test spawning multiple threads somewhere?

**Comment by khatchad** [comment]
> Hi @khatchad it's not clear to me this is an issue with multithreading. Do you have evidence of that?

Good point. No. I forgot that `ConcurrentModificationException` can also happen serially.

> Like is this test spawning multiple threads somewhere?

We setup `com.ibm.wala.cast.python.ml` to run tests concurrently, which is why I thought that this was happening due to parallelization.

**Comment by khatchad** [comment]
Here is where the trace starts in our code:

https://github.com/wala/ML/blob/d9a3d6be01441474acdf67c81ca62b8323598375/com.ibm.wala.cast.python.ml.test/source/com/ibm/wala/cast/python/ml/test/TestTensorflow2Model.java#L1504

That method could run concurrently if a test are executed in parallel. We are running the tests in parallel here, one thread per core:

https://github.com/wala/ML/blame/d9a3d6be01441474acdf67c81ca62b8323598375/pom.xml#L136-L137

**Comment by khatchad** [comment]
It also doesn't always occur, which makes me think that the nondeterminism is due to parallelism.

**Comment by msridhar** [comment]
@khatchad see #1379 for a potential fix.  Do we need a release after this lands to properly test the fix?

**Comment by khatchad** [comment]
> @khatchad see #1379 for a potential fix.  Do we need a release after this lands to properly test the fix?

Thanks! I can try to patch and monitor to see if it happens again. It's intermittent.

**Comment by msridhar** [comment]
> Thanks! I can try to patch and monitor to see if it happens again. It's intermittent.

Are you able to rely on some kind of snapshot version for your CI builds?

**Comment by khatchad** [comment]
I think so. I'll give it a shot.

**Comment by khatchad** [comment]
> > Thanks! I can try to patch and monitor to see if it happens again. It's intermittent.
> 
> Are you able to rely on some kind of snapshot version for your CI builds?

Looks like the WALA version is specified here:

https://github.com/wala/ML/blob/d9a3d6be01441474acdf67c81ca62b8323598375/pom.xml#L32

I believe I can stick in a snapshot version.

**Comment by khatchad** [comment]
I've created https://github.com/wala/ML/pull/174, but it looks like there's some compilation errors from upgrading from WALA 1.6.0 to 1.6.4-SNAPSHOT.
