### ISSUE TITLE
A runtime crash of points to analysis

### ISSUE THREAD

**Issue by tisble** [wala/WALA#1390]
Hi, I used Wala to perform points-to analysis for my project, but found a runtime crash due to type cast.

#### Code Example
```java
package org.example;
public class Example {
    static {
        foo(new C1());
    }
    public static void foo(C c) {
        System.out.println(c);
    }
    public static void main(String[] args) {
        // ......my code
    }
}
class C {}
class C1 extends C {}
```
#### My Wala Analysis Code 
```java
AnalysisScope scope = AnalysisScopeReader.instance.makeJavaBinaryAnalysisScope("IN", walaExclusionFile);
IClassHierarchy cha = ClassHierarchyFactory.make(scope);
Iterable<Entrypoint> entryPoints = Util.makeMainEntrypoints(cha); // default entry: main method
AnalysisOptions options = new AnalysisOptions(scope, entryPoints);
AnalysisCache cache = new AnalysisCacheImpl();
CallGraphBuilder<InstanceKey> builder = Util.makeZeroCFABuilder(Language.JAVA, options, cache, cha);
CallGraph cg = builder.makeCallGraph(options, null);
PointerAnalysis<InstanceKey> pointerAnalysis = builder.getPointerAnalysis();
for (PointerKey pk : pointerAnalysis.getPointerKeys()) {
    if (pk instanceof LocalPointerKey lpk) {
        String methodName = lpk.getNode().getMethod().getName().toString();
        if (methodName.equals("foo")) {
            ClassLoaderReference clr = lpk.getNode().getMethod().getDeclaringClass().getClassLoader().getReference();
            if (clr.equals(ClassLoaderReference.Application)) {
                if (lpk.isParameter()) {
                    for (InstanceKey ik : pointerAnalysis.getPointsToSet(lpk)) {
                        Iterator<Pair<CGNode, NewSiteReference>> iterator = ik.getCreationSites(cg);
                        while (iterator.hasNext()) {
                            Pair<CGNode, NewSiteReference> pair = iterator.next(); // crash here
                        }
                    }
                }
            }
        }
    }
}
```
#### Exception
```
java.lang.ClassCastException: class com.ibm.wala.ipa.callgraph.DelegatingContext cannot be cast to class com.ibm.wala.analysis.reflection.GetMethodContext (com.ibm.wala.ipa.callgraph.DelegatingContext and com.ibm.wala.analysis.reflection.GetMethodContext are in unnamed module of loader 'app')

	at com.ibm.wala.analysis.reflection.GetMethodContextInterpreter.iterateNewSites(GetMethodContextInterpreter.java:140)
	at com.ibm.wala.ipa.callgraph.propagation.rta.DelegatingRTAContextInterpreter.iterateNewSites(DelegatingRTAContextInterpreter.java:48)
	at com.ibm.wala.ipa.callgraph.propagation.rta.DelegatingRTAContextInterpreter.iterateNewSites(DelegatingRTAContextInterpreter.java:48)
	at com.ibm.wala.ipa.callgraph.impl.ExplicitCallGraph$ExplicitNode.iterateNewSites(ExplicitCallGraph.java:321)
	at com.ibm.wala.ipa.callgraph.propagation.ConcreteTypeKey$1.makeInner(ConcreteTypeKey.java:103)
	at com.ibm.wala.ipa.callgraph.propagation.ConcreteTypeKey$1.makeInner(ConcreteTypeKey.java:98)
	at com.ibm.wala.util.collections.ComposedIterator.advanceOuter(ComposedIterator.java:30)
	at com.ibm.wala.util.collections.ComposedIterator.next(ComposedIterator.java:57)
```

Wala version: 1.6.2

**Comment by msridhar** [comment]
@tisble thanks for the bug reports.  Can you retry this one on version 1.6.4?  I think I fixed this one already.

**Comment by tisble** [comment]
Thanks for you help. I have retried it with 1.6.4 and it worked successfully.
