### ISSUE TITLE
Fix Java7CallGraphTest on Windows

### ISSUE THREAD

**Issue by msridhar** [wala/WALA#168]
On [AppVeyor](https://ci.appveyor.com/project/msridhar/wala/build/1.0.6) the `testOcamlHelloHash` test fails with:
```
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:145)
	at com.ibm.wala.core.tests.callGraph.Java7CallGraphTest.testOCamlJar(Java7CallGraphTest.java:54)
	at com.ibm.wala.core.tests.callGraph.Java7CallGraphTest.testOcamlHelloHash(Java7CallGraphTest.java:46)
```

Hard to tell what is going on.

**Comment by liangkehai** [comment]
String a ="asd";
