### ISSUE TITLE
regression test failure: "too much memory"

### ISSUE THREAD

**Issue by liblit** [wala/WALA#225]
I am currently seeing a failing regression test when running `mvn --batch-mode --quiet --define skipAfterFailureCount=1 clean verify`:

```
Running com.ibm.wala.cast.js.rhino.callgraph.fieldbased.test.FieldBasedCGGamesTest
Tests run: 8, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 153.351 sec <<< FAILURE!
testRiverRaider(com.ibm.wala.cast.js.rhino.callgraph.fieldbased.test.FieldBasedCGGamesTest)  Time elapsed: 26.325 sec  <<< ERROR!
com.ibm.wala.util.CancelException: too much memory
	at com.ibm.wala.util.CancelException.make(CancelException.java:31)
	at com.ibm.wala.util.MonitorUtil.throwExceptionIfCanceled(MonitorUtil.java:75)
	at com.ibm.wala.cast.js.callgraph.fieldbased.WorklistBasedOptimisticCallgraphBuilder.extractCallGraphEdges(WorklistBasedOptimisticCallgraphBuilder.java:90)
	at com.ibm.wala.cast.js.callgraph.fieldbased.FieldBasedCallGraphBuilder.extract(FieldBasedCallGraphBuilder.java:171)
	at com.ibm.wala.cast.js.callgraph.fieldbased.FieldBasedCallGraphBuilder.extract(FieldBasedCallGraphBuilder.java:143)
	at com.ibm.wala.cast.js.callgraph.fieldbased.FieldBasedCallGraphBuilder.buildCallGraph(FieldBasedCallGraphBuilder.java:127)
	at com.ibm.wala.cast.js.test.FieldBasedCGUtil.buildCG(FieldBasedCGUtil.java:118)
	at com.ibm.wala.cast.js.test.FieldBasedCGUtil.buildPageCG(FieldBasedCGUtil.java:95)
	at com.ibm.wala.cast.js.test.FieldBasedCGUtil.buildCG(FieldBasedCGUtil.java:73)
	at com.ibm.wala.cast.js.rhino.callgraph.fieldbased.test.AbstractFieldBasedTest.runTest(AbstractFieldBasedTest.java:45)
	at com.ibm.wala.cast.js.rhino.callgraph.fieldbased.test.AbstractFieldBasedTest.runTestExceptOnTravis(AbstractFieldBasedTest.java:60)
	at com.ibm.wala.cast.js.rhino.callgraph.fieldbased.test.FieldBasedCGGamesTest.testRiverRaider(FieldBasedCGGamesTest.java:33)
```

This is appearing in the current `master` head: d73b11fd8f47c27f63450f14ad3c0848269942fe. I am also seeing it at least as far back in the history as 8ebfd7615cad588ece58bb5858d447e16c658933, perhaps farther. Apparently the Travis-CI test environment is not triggering this, though, or we would have been seeing failures there too. I am running on a Fedora 26 machine with `java-1.8.0-openjdk-headless-1.8.0.141-1.b16.fc26.x86_64`, but that environment has worked fine for me before.

Does anyone have any ideas as to what is going on here?

**Comment by juliandolby** [comment]
This test does not run on Travis CI, partly because it is so resource hungry.  When I run this on my laptop, I typically give those tests -Xmx2G option; I ran it that way just now, and it passed.

  — Julian

**Comment by liblit** [comment]
Thanks, @juliandolby; that’s helpful. How should I run `mvn` so that it, in turn, runs this or all tests with `-Xmx2G`? Or as an alternative, how to I mimic whatever Travis-CI is doing that allows it to skip this test entirely?

**Comment by juliandolby** [comment]
I typically use ‘export _JAVA_OPTIONS=-Xmx2G’ before running mvn; that makes all Java jobs use that heap limit.  A bit brute-force, but my laptop has ample memory. :)

**Comment by juliandolby** [comment]
These tests are guarded by the following check:

    if (System.getenv("TRAVIS") == null) {
      return runTest(url, assertions, builderTypes);
    } else {
      return null;
    }

so if you set the environment variable TRAVIS to some value, that will prevent these hungry tests from running.

**Comment by liblit** [comment]
Thanks for the info, @juliandolby, covering both how to run the tests with more memory and how to skip them in the manner of Travis-CI. Much appreciated.

**Comment by liblit** [comment]
I closed this issue because @juliandolby provided the information I needed. But it occurs to me that we now have a code base that *fails* its regression test suite by *default*. It only passes the suite if either `_JAVA_OPTIONS` or `TRAVIS` is set in the environment, neither of which is documented or automated.

Is failure-by-default really what we want? I claim that it is not. So I’m reopening this issue to suggest that the defaults should change.
