### ISSUE TITLE
Running WALA-start on Intellij

### ISSUE THREAD

**Issue by sohah** [wala/WALA#249]
Hello,

I am trying to use WALA for the first time. I cloned WALA-start into intellij. Building went fine but when I tried to run the ScopeFileCallGraph with these arguments -scopeFile /Users/.../helloworld.class -mainClass  helloworld
 
i get the following exception:
Exception in thread "main" java.util.NoSuchElementException
	at java.util.StringTokenizer.nextToken(StringTokenizer.java:349)
	at com.ibm.wala.util.config.AnalysisScopeReader.processScopeDefLine(AnalysisScopeReader.java:148)
	at com.ibm.wala.util.config.AnalysisScopeReader.read(AnalysisScopeReader.java:80)
	at com.ibm.wala.util.config.AnalysisScopeReader.readJavaScope(AnalysisScopeReader.java:53)
	at com.ibm.wala.examples.drivers.ScopeFileCallGraph.main(ScopeFileCallGraph.java:70)

Any idea what is going on? What is it that i'm doing wrong?

Much appreciated!

**Comment by bupt01** [comment]
Has the problem been solved?

**Comment by msridhar** [comment]
Sorry for never responding on this issue.  For the original example, the `-scopeFile` argument should point to a [scope file](https://github.com/wala/WALA/wiki/Analysis-Scope), not a class file.  Does that fix the problem?
