### ISSUE TITLE
How to create CFG from .apk file?

### ISSUE THREAD

**Issue by vngkv123** [wala/WALA#304]
I'm new in WALA, but i can't see example code to build CFG from .apk file.
How to code to do that? :(

**Comment by juliandolby** [comment]
Have you tried APKCallGraphDriver?

**Comment by lczxxx123** [comment]
I tried to run APKCallGraphDriver.
(1)However, first i left the /libs empty, then i meet with
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.lang.IllegalStateException: Could not create a entrypoint callsites: 1. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Application,Lcom/example/test/test1/B> No superclass found for <Application,Lcom/example/test/test1/B> Superclass name Landroid/app/Service
```

(2)if i put something like android.jar or support-v4-26.1.0-sources.jar into /libs, i will meet with
```
java.lang.NullPointerException: entry
	at java.util.zip.ZipFile.getInputStream(ZipFile.java:346)
	at java.util.jar.JarFile.getInputStream(JarFile.java:447)
	at com.ibm.wala.dalvik.classLoader.DexFileModule.<init>(DexFileModule.java:99)
	at com.ibm.wala.dalvik.classLoader.DexFileModule.make(DexFileModule.java:80)
	at com.ibm.wala.dalvik.util.AndroidAnalysisScope.setUpAndroidAnalysisScope(AndroidAnalysisScope.java:52)
	at com.ibm.wala.dalvik.test.util.Util.makeDalvikScope(Util.java:104)
	at com.ibm.wala.dalvik.test.callGraph.DalvikCallGraphTestBase.makeAPKCallGraph(DalvikCallGraphTestBase.java:111)
	at com.ibm.wala.dalvik.drivers.APKCallGraphDriver.lambda$0(APKCallGraphDriver.java:119)
	at com.ibm.wala.util.io.FileUtil.recurseFiles(FileUtil.java:198)
	at com.ibm.wala.dalvik.drivers.APKCallGraphDriver.main(APKCallGraphDriver.java:71)
```
So what's the parameter "androidLibs" mean in 
`public static Pair<CallGraph, PointerAnalysis<InstanceKey>> makeAPKCallGraph(URI[] androidLibs, File androidAPIJar, String apkFileName, IProgressMonitor monitor, ReflectionOptions policy)`
mean?
And how can i add reference to avoid problems in (2)? (if i can)
Thank you for your reply!
