### ISSUE TITLE
Exception when building call graph for JavaScript

### ISSUE THREAD

**Issue by thanhtoantnt** [wala/WALA#307]
I am following this article to build JavaScript call graph:
http://wala.sourceforge.net/wiki/index.php/Getting_Started:JavaScript_frontend#Building_call_graphs
I run the two instructions and made sure dir and name are correct directory and file name.
```
com.ibm.wala.cast.js.ipa.callgraph.JSCallGraphUtil.setTranslatorFactory(new CAstRhinoTranslatorFactory());
CallGraph CG = com.ibm.wala.cast.js.test.JSCallGraphBuilderUtil.makeScriptCG(dir, name);
```

And I got the following error:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/mozilla/javascript/ErrorReporter
	at com.ibm.wala.cast.js.translator.CAstRhinoTranslator.<init>(CAstRhinoTranslator.java:19)
	at com.ibm.wala.cast.js.translator.CAstRhinoTranslatorFactory.make(CAstRhinoTranslatorFactory.java:21)
	at com.ibm.wala.cast.js.loader.JavaScriptLoader.getTranslatorToCAst(JavaScriptLoader.java:807)
	at com.ibm.wala.cast.loader.CAstAbstractModuleLoader.translateModuleEntryToCAst(CAstAbstractModuleLoader.java:156)
	at com.ibm.wala.cast.loader.CAstAbstractModuleLoader.translateModuleToCAst(CAstAbstractModuleLoader.java:197)
	at com.ibm.wala.cast.loader.CAstAbstractModuleLoader.init(CAstAbstractModuleLoader.java:119)
	at com.ibm.wala.cast.loader.SingleClassLoaderFactory.getLoader(SingleClassLoaderFactory.java:42)
	at com.ibm.wala.ipa.cha.ClassHierarchy.<init>(ClassHierarchy.java:232)
	at com.ibm.wala.ipa.cha.ClassHierarchy.<init>(ClassHierarchy.java:171)
	at com.ibm.wala.ipa.cha.ClassHierarchyFactory.make(ClassHierarchyFactory.java:72)
	at com.ibm.wala.cast.js.ipa.callgraph.correlations.CorrelationFinder.findCorrelatedAccesses(CorrelationFinder.java:287)
	at com.ibm.wala.cast.js.ipa.callgraph.correlations.CorrelationFinder.findCorrelatedAccesses(CorrelationFinder.java:280)
	at com.ibm.wala.cast.js.ipa.callgraph.correlations.CorrelationFinder.findCorrelatedAccesses(CorrelationFinder.java:275)
	at com.ibm.wala.cast.js.ipa.callgraph.correlations.extraction.CorrelatedPairExtractorFactory.<init>(CorrelatedPairExtractorFactory.java:32)
	at com.ibm.wala.cast.js.test.JSCallGraphBuilderUtil.makeScriptCGBuilder(JSCallGraphBuilderUtil.java:98)
	at com.ibm.wala.cast.js.test.JSCallGraphBuilderUtil.makeScriptCG(JSCallGraphBuilderUtil.java:157)
	at com.ibm.wala.cast.js.test.JSCallGraphBuilderUtil.makeScriptCG(JSCallGraphBuilderUtil.java:148)
	at com.ibm.wala.examples.drivers.JSCallGraphTest.main(JSCallGraphTest.java:29)
Caused by: java.lang.ClassNotFoundException: org.mozilla.javascript.ErrorReporter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more
```

Is anyone know how to fix this problem?

**Comment by msridhar** [comment]
What is your config?  Are you pulling in jars from Maven Central or building from source?  If the latter, did you run `mvn clean verify -DskipTests=true -q` (see [here](https://github.com/wala/WALA/wiki/Getting-Started#building-the-code))?

**Comment by thanhtoantnt** [comment]
I figured it out. I build from source using Maven and then include jar files to Java Build Path but I didn't add some libraries. The above error is by Rhino is not added. Thanks for your response.
