### ISSUE TITLE
Exception when getting the IR of certain application methods in Android.

### ISSUE THREAD

**Issue by sifislag** [wala/WALA#324]
Hello,
Since moving from version 1.4.3 to version 1.5.0-SNAPSHOT we've been having some issues with Android. When going through the class hierarchy and generating/caching the IR of each method we've been getting an IllegalArgumentException for some methods of the apk.
````
java.lang.IllegalArgumentException: invalid descriptor: V
at com.ibm.wala.util.strings.StringStuff.parseForReturnTypeName(StringStuff.java:149)
at com.ibm.wala.types.Descriptor.findOrCreate(Descriptor.java:64)
at com.ibm.wala.types.Descriptor.findOrCreateUTF8(Descriptor.java:93)
at com.ibm.wala.types.MethodReference.findOrCreate(MethodReference.java:148)
at com.ibm.wala.dalvik.ssa.DexSSABuilder$SymbolicPropagator$NodeVisitor.visitInvoke(DexSSABuilder.java:792)
at com.ibm.wala.dalvik.dex.instructions.Invoke.visit(Invoke.java:229)
at com.ibm.wala.dalvik.ssa.AbstractIntRegisterMachine$BasicRegisterFlowProvider.flow(AbstractIntRegisterMachine.java:862)
at com.ibm.wala.dalvik.ssa.AbstractIntRegisterMachine$1$1.evaluate(AbstractIntRegisterMachine.java:139)
at com.ibm.wala.dalvik.ssa.AbstractIntRegisterMachine$1$1.evaluate(AbstractIntRegisterMachine.java:1)
at com.ibm.wala.fixpoint.UnaryStatement.evaluate(UnaryStatement.java:35)
at com.ibm.wala.fixedpoint.impl.AbstractFixedPointSolver.solve(AbstractFixedPointSolver.java:152)
at com.ibm.wala.dalvik.ssa.AbstractIntRegisterMachine.solve(AbstractIntRegisterMachine.java:257)
at com.ibm.wala.dalvik.ssa.DexSSABuilder.build(DexSSABuilder.java:1361)
at com.ibm.wala.dalvik.classLoader.DexIRFactory$1.<init>(DexIRFactory.java:102)
at com.ibm.wala.dalvik.classLoader.DexIRFactory.makeIR(DexIRFactory.java:69)
at com.ibm.wala.ssa.SSACache.findOrCreateIR(SSACache.java:78)
at com.ibm.wala.ipa.callgraph.AnalysisCache.getIR(AnalysisCache.java:74)
...
````
I've had the issue with all 4 apks that I tried. One of these apks is the official wikipedia application version 2.7.224-r-2018-01-06(224) which is the one we've used a lot as a benchmark when building our WALA based fact generator.
(https://www.apkmirror.com/apk/wikimedia-foundation/wikipedia/wikipedia-2-7-224-release/wikipedia-2-7-224-r-2018-01-06-android-apk-download/)
For the wikipedia app 38 of the 37.748 methods inside the apk throw the exception(output of the program below):
````
Error while creating IR for method: < Application, Landroid/support/design/internal/ForegroundLinearLayout, onLayout(ZIIII)V >
java.lang.IllegalArgumentException: invalid descriptor: V
Error while creating IR for method: < Application, Lorg/apache/commons/lang3/text/ExtendedMessageFormat, applyPattern(Ljava/lang/String;)V >
java.lang.IllegalArgumentException: invalid descriptor: Ljava/lang/String;
Error while creating IR for method: < Application, Lcom/facebook/samples/zoomable/ZoomableDraweeView, onLayout(ZIIII)V >
java.lang.IllegalArgumentException: invalid descriptor: V
Error while creating IR for method: < Application, Landroid/support/v7/widget/AppCompatButton, onLayout(ZIIII)V >
java.lang.IllegalArgumentException: invalid descriptor: V
Error while creating IR for method: < Application, Landroid/support/v7/widget/ActionBarContainer, onLayout(ZIIII)V >
java.lang.IllegalArgumentException: invalid descriptor: V
Error while creating IR for method: < Application, Landroid/support/design/widget/AppBarLayout$Behavior, onMeasureChild(Landroid/support/design/widget/CoordinatorLayout;Landroid/support/design/widget/AppBarLayout;IIII)Z >
java.lang.IllegalArgumentException: invalid descriptor: Z
Error while creating IR for method: < Application, Landroid/support/design/widget/TabLayout$SlidingTabStrip, onLayout(ZIIII)V >
java.lang.IllegalArgumentException: invalid descriptor: V
Error while creating IR for method: < Application, Landroid/support/v7/widget/ActionMenuPresenter$OverflowMenuButton, setFrame(IIII)Z >
java.lang.IllegalArgumentException: invalid descriptor: Z
Error while creating IR for method: < Application, Landroid/support/design/widget/AppBarLayout$ScrollingViewBehavior, onMeasureChild(Landroid/support/design/widget/CoordinatorLayout;Landroid/view/View;IIII)Z >
java.lang.IllegalArgumentException: invalid descriptor: Z
Error while creating IR for method: < Application, Landroid/support/v7/widget/GridLayoutManager, onFocusSearchFailed(Landroid/view/View;ILandroid/support/v7/widget/RecyclerView$Recycler;Landroid/support/v7/widget/RecyclerView$State;)Landroid/view/View; >
java.lang.IllegalArgumentException: invalid descriptor: Landroid/view/View;
Error while creating IR for method: < Application, Landroid/support/v7/widget/ActionMenuView, onLayout(ZIIII)V >
java.lang.IllegalArgumentException: invalid descriptor: V
Error while creating IR for method: < Application, Landroid/support/v4/app/BaseFragmentActivityApi14, startIntentSenderForResult(Landroid/content/IntentSender;ILandroid/content/Intent;III)V >
java.lang.IllegalArgumentException: invalid descriptor: V
Error while creating IR for method: < Application, Landroid/support/v7/widget/helper/ItemTouchUIUtilImpl$Api21Impl, onDraw(Landroid/graphics/Canvas;Landroid/support/v7/widget/RecyclerView;Landroid/view/View;FFIZ)V >
java.lang.IllegalArgumentException: invalid descriptor: V
Error while creating IR for method: < Application, Landroid/support/v4/widget/DrawerLayout, drawChild(Landroid/graphics/Canvas;Landroid/view/View;J)Z >
java.lang.IllegalArgumentException: invalid descriptor: Z
Error while creating IR for method: < Application, Landroid/support/v4/widget/NestedScrollView, onLayout(ZIIII)V >
java.lang.IllegalArgumentException: invalid descriptor: V
Error while creating IR for method: < Application, Landroid/support/v4/view/ViewPager, onDraw(Landroid/graphics/Canvas;)V >
java.lang.IllegalArgumentException: invalid descriptor: V
Error while creating IR for method: < Application, Lcom/rd/PageIndicatorView, onLayout(ZIIII)V >
java.lang.IllegalArgumentException: invalid descriptor: V
Error while creating IR for method: < Application, Landroid/support/v7/widget/ContentFrameLayout, onMeasure(II)V >
java.lang.IllegalArgumentException: invalid descriptor: V
Error while creating IR for method: < Application, Landroid/support/design/widget/BottomSheetBehavior, onNestedPreFling(Landroid/support/design/widget/CoordinatorLayout;Landroid/view/View;Landroid/view/View;FF)Z >
java.lang.IllegalArgumentException: invalid descriptor: Z
Error while creating IR for method: < Application, Landroid/support/v7/widget/AppCompatPopupWindow, update(Landroid/view/View;IIII)V >
java.lang.IllegalArgumentException: invalid descriptor: V
Error while creating IR for method: < Application, Landroid/support/v7/widget/SearchView, onLayout(ZIIII)V >
java.lang.IllegalArgumentException: invalid descriptor: V
Error while creating IR for method: < Application, Lorg/wikipedia/views/SwipeableItemTouchHelperCallback, onChildDraw(Landroid/graphics/Canvas;Landroid/support/v7/widget/RecyclerView;Landroid/support/v7/widget/RecyclerView$ViewHolder;FFIZ)V >
java.lang.IllegalArgumentException: invalid descriptor: V
Error while creating IR for method: < Application, Landroid/support/v4/app/BaseFragmentActivityApi16, startIntentSenderForResult(Landroid/content/IntentSender;ILandroid/content/Intent;IIILandroid/os/Bundle;)V >
java.lang.IllegalArgumentException: invalid descriptor: V
Error while creating IR for method: < Application, Landroid/support/v4/app/FragmentActivity, startIntentSenderForResult(Landroid/content/IntentSender;ILandroid/content/Intent;III)V >
java.lang.IllegalArgumentException: invalid descriptor: V
Error while creating IR for method: < Application, Landroid/support/v4/app/FragmentActivity, startIntentSenderForResult(Landroid/content/IntentSender;ILandroid/content/Intent;IIILandroid/os/Bundle;)V >
java.lang.IllegalArgumentException: invalid descriptor: V
Error while creating IR for method: < Application, Landroid/support/v7/widget/SwitchCompat, draw(Landroid/graphics/Canvas;)V >
java.lang.IllegalArgumentException: invalid descriptor: V
Error while creating IR for method: < Application, Landroid/support/v7/widget/SwitchCompat, onDraw(Landroid/graphics/Canvas;)V >
java.lang.IllegalArgumentException: invalid descriptor: V
Error while creating IR for method: < Application, Landroid/support/v7/widget/SwitchCompat, onLayout(ZIIII)V >
java.lang.IllegalArgumentException: invalid descriptor: V
Error while creating IR for method: < Application, Landroid/support/design/widget/TextInputLayout, onLayout(ZIIII)V >
java.lang.IllegalArgumentException: invalid descriptor: V
Error while creating IR for method: < Application, Landroid/support/v7/widget/ButtonBarLayout, onMeasure(II)V >
java.lang.IllegalArgumentException: invalid descriptor: V
Error while creating IR for method: < Application, Lorg/wikipedia/page/leadimages/PageHeaderView, onLayout(ZIIII)V >
java.lang.IllegalArgumentException: invalid descriptor: V
Error while creating IR for method: < Application, Lcom/mapbox/mapboxsdk/annotations/BubbleLayout, onLayout(ZIIII)V >
java.lang.IllegalArgumentException: invalid descriptor: V
Error while creating IR for method: < Application, Landroid/support/design/widget/CollapsingToolbarLayout, onLayout(ZIIII)V >
java.lang.IllegalArgumentException: invalid descriptor: V
Error while creating IR for method: < Application, Landroid/support/v4/graphics/TypefaceCompatApi26Impl, createFromResourcesFontFile(Landroid/content/Context;Landroid/content/res/Resources;ILjava/lang/String;I)Landroid/graphics/Typeface; >
java.lang.IllegalArgumentException: invalid descriptor: Landroid/graphics/Typeface;
Error while creating IR for method: < Application, Lorg/wikipedia/edit/preview/EditPreviewFragment, onActivityCreated(Landroid/os/Bundle;)V >
java.lang.IllegalArgumentException: invalid descriptor: V
Error while creating IR for method: < Application, Landroid/support/design/widget/BaseTransientBottomBar$SnackbarBaseLayout, onLayout(ZIIII)V >
java.lang.IllegalArgumentException: invalid descriptor: V
Error while creating IR for method: < Application, Landroid/support/design/widget/AppBarLayout, onLayout(ZIIII)V >
java.lang.IllegalArgumentException: invalid descriptor: V
Error while creating IR for method: < Application, Landroid/support/v7/widget/AppCompatTextView, onLayout(ZIIII)V >
java.lang.IllegalArgumentException: invalid descriptor: V
````
Minimal example that demonstrates the error:
```java
    AnalysisScope scope;
    if(walaParameters._android)
        scope = WalaScopeReader.setUpAndroidAnalysisScope(walaParameters._inputs, "", walaParameters._platformLibraries, walaParameters._appLibraries);
    else
        scope = WalaScopeReader.setupJavaAnalysisScope(walaParameters._inputs,"", walaParameters._platformLibraries, walaParameters._appLibraries);

    ClassHierarchy cha = null;
    try {
        cha = ClassHierarchyFactory.make(scope);
    } catch (ClassHierarchyException e) {
        e.printStackTrace();
    }
    Iterator<IClass> classes = cha.iterator();
    IAnalysisCacheView cache;
    if(walaParameters._android)
        cache = new AnalysisCacheImpl(new DexIRFactory());
    else
        cache = new AnalysisCacheImpl();

    IClass klass;
    while (classes.hasNext()) {
        klass = classes.next();
        for(IMethod m: klass.getDeclaredMethods()) {
            try {
                cache.getIR(m);
            }catch (Throwable e){
                System.out.println("Error while creating IR for method: " + m.getReference() + "\n"+ e);
            }
        }
    }
```
Scope creation method:
```java
public static AnalysisScope setUpAndroidAnalysisScope(List<String> inputs, String exclusions, List<String> androidLibs, List<String> appLibs) throws IOException {
    AnalysisScope scope;
    scope = AnalysisScope.createJavaAnalysisScope();

    File exclusionsFile = new File(exclusions);
    try (final InputStream fs = exclusionsFile.exists()? new FileInputStream(exclusionsFile): FileProvider.class.getClassLoader().getResourceAsStream(exclusionsFile.getName())) {
        scope.setExclusions(new FileOfClasses(fs));
    }

    scope.setLoaderImpl(ClassLoaderReference.Primordial,
            "com.ibm.wala.dalvik.classLoader.WDexClassLoaderImpl");

    for(String androidLib : androidLibs) {
        if (androidLib.endsWith(".apk")) {
            scope.addToScope(ClassLoaderReference.Primordial, DexFileModule.make(new File(androidLib)));
        } else {
            final JarFile jar = new JarFile(new File(androidLib));
            scope.addToScope(ClassLoaderReference.Primordial, new JarFileModule(jar));
        }
    }

    scope.setLoaderImpl(ClassLoaderReference.Extension,
            "com.ibm.wala.dalvik.classLoader.WDexClassLoaderImpl");

    for(String appLib : appLibs) {
        if (appLib.endsWith(".apk")) {
            scope.addToScope(ClassLoaderReference.Extension, DexFileModule.make(new File(appLib)));
        } else {
            final JarFile jar = new JarFile(new File(appLib));
            scope.addToScope(ClassLoaderReference.Extension, new JarFileModule(jar));
        }
    }


    scope.setLoaderImpl(ClassLoaderReference.Application,
            "com.ibm.wala.dalvik.classLoader.WDexClassLoaderImpl");

    for(String input: inputs)
        scope.addToScope(ClassLoaderReference.Application, DexFileModule.make(new File(input)));

    return scope;
}
```

Thanks,
Sifis.

**Comment by jerryhero** [comment]
how to get the 1.5.0 version?

**Comment by sifislag** [comment]
I built it myself from sources.

**Comment by msridhar** [comment]
@sifislag is this fixed on WALA master?

**Comment by sifislag** [comment]
@msridhar I just checked and it is still has the same issues.

**Comment by lczxxx123** [comment]
when i use 1.4.3 version, that's ok, but when i use 1.5.0, i meet the same exception

**Comment by juliandolby** [comment]
I think I found a bug that is responsible for this.  Can you try now with the latest WALA master, and see if the problem still happens?

**Comment by sifislag** [comment]
I just tried and it seems fixed now.
Thanks!

**Comment by juliandolby** [comment]
If stuff seems to work, should we close this issue?

**Comment by sifislag** [comment]
You should.
