### ISSUE TITLE
Errors during Call Graph Creation on Android

### ISSUE THREAD

**Issue by Jacoppy** [wala/WALA#348]
Hi,
I am still working on WALA.
I am trying now to create a Complete Call Graph from an Android Application but I am encountering random errors, depending on the apk I analyze.
This is my code : 

`public static void main(String[] args) {
		//File apk = new File(args[0]);
		File apk = new File("/home/jacopo/Documents/work/good_apps/00ADBDEE7ED68BB4C243F30EA0BABD56C034574303783924DC9654F2916A43E8.apk");
		String Activity_searched = "com/yteu/hfdh/Bona";
		try {
			//timeout = Integer.parseInt(args[1]);
			timeout = 60000;
			System.err.println("timeout is " + timeout);
		} catch (Throwable e) {
			// no timeout specified
		}
		System.err.println("Analyzing " + apk + "...");
		try {
			long time = System.currentTimeMillis();
			Pair<CallGraph, PointerAnalysis<InstanceKey>> CG;
			final long startTime = System.currentTimeMillis();
			
			IProgressMonitor pm = new IProgressMonitor() {
				private boolean cancelled = false;

				@Override
				public void beginTask(String task, int totalWork) {
					// TODO Auto-generated method stub	
				}

				@Override
				public void subTask(String subTask) {
					// TODO Auto-generated method stub
				}

				@Override
				public void cancel() {
					cancelled = true;
				}

				@Override
				public boolean isCanceled() {
					if (System.currentTimeMillis() - startTime > timeout) {
						cancelled = true;
					}
					return cancelled;
				}

				@Override
				public void done() {
					// TODO Auto-generated method stub					
				}

				@Override
				public void worked(int units) {
					// TODO Auto-generated method stub
				}

				@Override
				public String getCancelMessage() {
					return "timeout";
				}	
			};
			
			File android = new File("/home/jacopo/Android/Sdk/platforms/android-28/android.jar");
			
			AnalysisScope scope = makeDalvikScope(null, android, apk.getAbsolutePath());
			final IClassHierarchy cha = ClassHierarchyFactory.make(scope);
			IAnalysisCacheView cache = new AnalysisCacheImpl(new DexIRFactory());
			Set<LocatorFlags> set = new HashSet<LocatorFlags>();
		    set.add(LocatorFlags.INCLUDE_CALLBACKS);
		    set.add(LocatorFlags.EP_HEURISTIC);
		    set.add(LocatorFlags.CB_HEURISTIC);
		    set.add(LocatorFlags.WITH_CTOR);
		    //set.add(LocatorFlags.WITH_SUPER);
		    AndroidEntryPointLocator eps = new AndroidEntryPointLocator(set);
		    List<AndroidEntryPoint> entryPoints = eps.getEntryPoints(cha);

		    assert ! entryPoints.isEmpty();
		    
		    AnalysisOptions options = new AnalysisOptions(scope, entryPoints);
	        options.setReflectionOptions(ReflectionOptions.FULL);
	        
	        SSAPropagationCallGraphBuilder cgb = com.ibm.wala.ipa.callgraph.impl.Util.makeZeroCFABuilder(Language.JAVA,options, cache, cha, scope);
	        CallGraph cg = cgb.makeCallGraph(options, pm);`

And this is the error thrown : 
`java.lang.IllegalArgumentException: invalid descriptor: V
	at com.ibm.wala.util.strings.StringStuff.parseForReturnTypeName(StringStuff.java:149)
	at com.ibm.wala.types.Descriptor.findOrCreate(Descriptor.java:64)
	at com.ibm.wala.types.Descriptor.findOrCreateUTF8(Descriptor.java:93)
	at com.ibm.wala.types.Descriptor.findOrCreateUTF8(Descriptor.java:84)
	at com.ibm.wala.dalvik.dex.instructions.Invoke.<init>(Invoke.java:73)
	at com.ibm.wala.dalvik.dex.instructions.Invoke$InvokeSuper.<init>(Invoke.java:110)
	at com.ibm.wala.dalvik.classLoader.DexIMethod.parseBytecode(DexIMethod.java:1739)
	at com.ibm.wala.dalvik.classLoader.DexIMethod.instructions(DexIMethod.java:3215)
	at com.ibm.wala.dalvik.classLoader.DexIMethod.getHandlers(DexIMethod.java:639)
	at com.ibm.wala.dalvik.classLoader.DexCFG.makeBasicBlocks(DexCFG.java:140)
	at com.ibm.wala.dalvik.classLoader.DexCFG.<init>(DexCFG.java:77)
	at com.ibm.wala.dalvik.classLoader.DexIRFactory.makeCFG(DexIRFactory.java:37)
	at com.ibm.wala.dalvik.classLoader.DexIRFactory.makeIR(DexIRFactory.java:58)
	at com.ibm.wala.ssa.SSACache.findOrCreateIR(SSACache.java:78)
	at com.ibm.wala.ipa.callgraph.AnalysisCache.getIR(AnalysisCache.java:74)
	at com.ibm.wala.ipa.callgraph.propagation.cfa.ContextInsensitiveSSAInterpreter.getIR(ContextInsensitiveSSAInterpreter.java:46)
	at com.ibm.wala.ipa.callgraph.propagation.cfa.DefaultSSAInterpreter.getIR(DefaultSSAInterpreter.java:57)
	at com.ibm.wala.ipa.callgraph.propagation.cfa.DelegatingSSAContextInterpreter.getIR(DelegatingSSAContextInterpreter.java:56)
	at com.ibm.wala.ipa.callgraph.impl.ExplicitCallGraph$ExplicitNode.getIR(ExplicitCallGraph.java:307)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.getTargetPointerKey(SSAPropagationCallGraphBuilder.java:2191)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.processCallingConstraints(SSAPropagationCallGraphBuilder.java:1640)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.processResolvedCall(SSAPropagationCallGraphBuilder.java:1593)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.access$2(SSAPropagationCallGraphBuilder.java:1571)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$DispatchOperator.lambda$1(SSAPropagationCallGraphBuilder.java:1745)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$CrossProductRec.rec(SSAPropagationCallGraphBuilder.java:531)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$CrossProductRec.lambda$0(SSAPropagationCallGraphBuilder.java:553)
	at com.ibm.wala.util.intset.SparseIntSet.foreach(SparseIntSet.java:438)
	at com.ibm.wala.util.intset.MutableSharedBitVectorIntSet.foreach(MutableSharedBitVectorIntSet.java:271)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$CrossProductRec.rec(SSAPropagationCallGraphBuilder.java:551)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$DispatchOperator$1.<init>(SSAPropagationCallGraphBuilder.java:1753)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$DispatchOperator.lambda$0(SSAPropagationCallGraphBuilder.java:1735)
	at com.ibm.wala.util.intset.SparseIntSet.foreach(SparseIntSet.java:438)
	at com.ibm.wala.util.intset.MutableSharedBitVectorIntSet.foreachExcludingInternal(MutableSharedBitVectorIntSet.java:300)
	at com.ibm.wala.util.intset.MutableSharedBitVectorIntSet.foreachExcluding(MutableSharedBitVectorIntSet.java:284)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$DispatchOperator.cpa(SSAPropagationCallGraphBuilder.java:1735)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$DispatchOperator.evaluate(SSAPropagationCallGraphBuilder.java:1781)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$DispatchOperator.evaluate(SSAPropagationCallGraphBuilder.java:1)
	at com.ibm.wala.fixedpoint.impl.GeneralStatement.evaluate(GeneralStatement.java:37)
	at com.ibm.wala.fixedpoint.impl.AbstractFixedPointSolver.incorporateNewStatement(AbstractFixedPointSolver.java:292)
	at com.ibm.wala.fixedpoint.impl.AbstractFixedPointSolver.newStatement(AbstractFixedPointSolver.java:438)
	at com.ibm.wala.ipa.callgraph.propagation.PropagationSystem.newSideEffect(PropagationSystem.java:580)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$ConstraintVisitor.visitInvokeInternal(SSAPropagationCallGraphBuilder.java:1180)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$ConstraintVisitor.visitInvoke(SSAPropagationCallGraphBuilder.java:1108)
	at com.ibm.wala.ssa.SSAInvokeInstruction.visit(SSAInvokeInstruction.java:85)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.addBlockInstructionConstraints(SSAPropagationCallGraphBuilder.java:290)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.addNodeInstructionConstraints(SSAPropagationCallGraphBuilder.java:261)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.unconditionallyAddConstraintsFromNode(SSAPropagationCallGraphBuilder.java:233)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.addConstraintsFromNode(SSAPropagationCallGraphBuilder.java:199)
	at com.ibm.wala.ipa.callgraph.propagation.PropagationCallGraphBuilder.addConstraintsFromNewNodes(PropagationCallGraphBuilder.java:336)
	at com.ibm.wala.ipa.callgraph.propagation.StandardSolver.solve(StandardSolver.java:58)
	at com.ibm.wala.ipa.callgraph.propagation.PropagationCallGraphBuilder.makeCallGraph(PropagationCallGraphBuilder.java:269)
	at `tutorial.examples.CreateSDGForAPK.main(CreateSDGForAPK.java:175)``

These errors appears when I use an SDK android.jar library, not the default function _libs()_ , which is the following : 
`private static URI[] libs() {
		File f = new File("libs");
		if (f.exists() && f.isDirectory()) {
			Set<URI> libs = HashSetFactory.make();
			for(File l : f.listFiles()) {
				String name = l.getName();
				if (name.endsWith("jar") || name.endsWith("dex")) {
					libs.add(l.toURI());
				}
			}

			return libs.toArray(new URI[ libs.size() ]);
		}

		return Util.androidLibs();
	}`

I am not using this function because actually I obtain a different callgraph in which some calls completely miss.
There is some ways by which I can fix this issue?
Thank you

**Comment by juliandolby** [comment]
Yes, I thought we had.  Are you using the latest WALA from github?  If so, could you make the APK available so that I can reproduce?

**Comment by Jacoppy** [comment]
Yes I cloned the repo 10-12 days ago so I guess is the latest version.
In the uploaded zip there are 2 apks.
The first one gives the error mentioned earlier, while the second one generates this one:
`
java.lang.IllegalArgumentException: invalid descriptor: Lcom/google/android/gms/games/PlayerEntity;
	at com.ibm.wala.util.strings.StringStuff.parseForReturnTypeName(StringStuff.java:153)
	at com.ibm.wala.types.Descriptor.findOrCreate(Descriptor.java:64)
	at com.ibm.wala.types.Descriptor.findOrCreateUTF8(Descriptor.java:93)
	at com.ibm.wala.types.Descriptor.findOrCreateUTF8(Descriptor.java:84)
	at com.ibm.wala.dalvik.dex.instructions.Invoke.<init>(Invoke.java:73)
	at com.ibm.wala.dalvik.dex.instructions.Invoke$InvokeSuper.<init>(Invoke.java:110)
	at com.ibm.wala.dalvik.classLoader.DexIMethod.parseBytecode(DexIMethod.java:1739)
	at com.ibm.wala.dalvik.classLoader.DexIMethod.instructions(DexIMethod.java:3215)
	at com.ibm.wala.dalvik.classLoader.DexIMethod.getHandlers(DexIMethod.java:639)
	at com.ibm.wala.dalvik.classLoader.DexCFG.makeBasicBlocks(DexCFG.java:140)
	at com.ibm.wala.dalvik.classLoader.DexCFG.<init>(DexCFG.java:77)
	at com.ibm.wala.dalvik.classLoader.DexIRFactory.makeCFG(DexIRFactory.java:37)
	at com.ibm.wala.dalvik.classLoader.DexIRFactory.makeIR(DexIRFactory.java:58)
	at com.ibm.wala.ssa.SSACache.findOrCreateIR(SSACache.java:78)
	at com.ibm.wala.ipa.callgraph.AnalysisCache.getIR(AnalysisCache.java:74)
	at com.ibm.wala.ipa.callgraph.propagation.cfa.ContextInsensitiveSSAInterpreter.getIR(ContextInsensitiveSSAInterpreter.java:46)
	at com.ibm.wala.ipa.callgraph.propagation.cfa.DefaultSSAInterpreter.getIR(DefaultSSAInterpreter.java:57)
	at com.ibm.wala.ipa.callgraph.propagation.cfa.DelegatingSSAContextInterpreter.getIR(DelegatingSSAContextInterpreter.java:56)
	at com.ibm.wala.ipa.callgraph.impl.ExplicitCallGraph$ExplicitNode.getIR(ExplicitCallGraph.java:307)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.getTargetPointerKey(SSAPropagationCallGraphBuilder.java:2191)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.processCallingConstraints(SSAPropagationCallGraphBuilder.java:1640)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.processResolvedCall(SSAPropagationCallGraphBuilder.java:1593)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.access$2(SSAPropagationCallGraphBuilder.java:1571)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$DispatchOperator.lambda$1(SSAPropagationCallGraphBuilder.java:1745)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$CrossProductRec.rec(SSAPropagationCallGraphBuilder.java:531)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$CrossProductRec.lambda$0(SSAPropagationCallGraphBuilder.java:553)
	at com.ibm.wala.util.intset.SparseIntSet.foreach(SparseIntSet.java:438)
	at com.ibm.wala.util.intset.MutableSharedBitVectorIntSet.foreach(MutableSharedBitVectorIntSet.java:271)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$CrossProductRec.rec(SSAPropagationCallGraphBuilder.java:551)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$DispatchOperator$1.<init>(SSAPropagationCallGraphBuilder.java:1753)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$DispatchOperator.lambda$0(SSAPropagationCallGraphBuilder.java:1735)
	at com.ibm.wala.util.intset.SparseIntSet.foreach(SparseIntSet.java:438)
	at com.ibm.wala.util.intset.MutableSharedBitVectorIntSet.foreachExcludingInternal(MutableSharedBitVectorIntSet.java:300)
	at com.ibm.wala.util.intset.MutableSharedBitVectorIntSet.foreachExcluding(MutableSharedBitVectorIntSet.java:284)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$DispatchOperator.cpa(SSAPropagationCallGraphBuilder.java:1735)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$DispatchOperator.evaluate(SSAPropagationCallGraphBuilder.java:1781)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$DispatchOperator.evaluate(SSAPropagationCallGraphBuilder.java:1)
	at com.ibm.wala.fixedpoint.impl.GeneralStatement.evaluate(GeneralStatement.java:37)
	at com.ibm.wala.fixedpoint.impl.AbstractFixedPointSolver.incorporateNewStatement(AbstractFixedPointSolver.java:292)
	at com.ibm.wala.fixedpoint.impl.AbstractFixedPointSolver.newStatement(AbstractFixedPointSolver.java:438)
	at com.ibm.wala.ipa.callgraph.propagation.PropagationSystem.newSideEffect(PropagationSystem.java:580)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$ConstraintVisitor.visitInvokeInternal(SSAPropagationCallGraphBuilder.java:1180)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$ConstraintVisitor.visitInvoke(SSAPropagationCallGraphBuilder.java:1108)
	at com.ibm.wala.ssa.SSAInvokeInstruction.visit(SSAInvokeInstruction.java:85)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.addBlockInstructionConstraints(SSAPropagationCallGraphBuilder.java:290)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.addNodeInstructionConstraints(SSAPropagationCallGraphBuilder.java:261)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.unconditionallyAddConstraintsFromNode(SSAPropagationCallGraphBuilder.java:233)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.addConstraintsFromNode(SSAPropagationCallGraphBuilder.java:199)
	at com.ibm.wala.ipa.callgraph.propagation.PropagationCallGraphBuilder.addConstraintsFromNewNodes(PropagationCallGraphBuilder.java:336)
	at com.ibm.wala.ipa.callgraph.propagation.StandardSolver.solve(StandardSolver.java:58)
	at com.ibm.wala.ipa.callgraph.propagation.PropagationCallGraphBuilder.makeCallGraph(PropagationCallGraphBuilder.java:269)
	at tutorial.examples.CreateSDGForAPK.main(CreateSDGForAPK.java:175)`

Thank you very much for the help :)
[for_git.zip](https://github.com/wala/WALA/files/2357503/for_git.zip)

**Comment by juliandolby** [comment]
see if my recent fixes help with this.  Get the latest WALA master and try this again.

**Comment by Jacoppy** [comment]
The issue of the first one is fixed, I got no expections back and the programs end normally. On the other hand for the second application, 002F3F9D69805FBD8D53ADF0ED2504F399D3BF4A419218800747E1D3A8BE0BBD.apk,  the analysis takes forever, probably the program get stuck, even if doesn't print out any error or exception.
In any case, thank you very much :))

**Comment by Jacoppy** [comment]
You are right, that setting was responsalbe for the endlessless process. Ok, So I have to tune it up correctly. Thank you very much for the help, I will close this issue now.
