### ISSUE TITLE
JarFileModule cannot be added to scope

### ISSUE THREAD

**Issue by reddr** [wala/WALA#355]
When using [AndroidAnalysisScope.setupAndroidAnalysisScope](https://github.com/wala/WALA/blob/master/com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/util/AndroidAnalysisScope.javal) to set up the scope with a Java Library for the androidLib argument, e.g. the Android SDK jar I receive the following exception:
`[FATAL EXCEPTION] analysis aborted: zip file closed
java.lang.IllegalStateException: zip file closed
  at java.util.zip.ZipFile.ensureOpen(java.base@9-internal/ZipFile.java:639)
  at java.util.zip.ZipFile.access$500(java.base@9-internal/ZipFile.java:73)
  at java.util.zip.ZipFile$ZipEntryIterator.<init>(java.base@9-internal/ZipFile.java:467)
  at java.util.zip.ZipFile.entries(java.base@9-internal/ZipFile.java:507)
  at java.util.jar.JarFile.access$401(java.base@9-internal/JarFile.java:132)
  at java.util.jar.JarFile$JarEntryIterator.<init>(java.base@9-internal/JarFile.java:537)
  at java.util.jar.JarFile$JarEntryIterator.<init>(java.base@9-internal/JarFile.java:534)
  at java.util.jar.JarFile.entries(java.base@9-internal/JarFile.java:609)
  at com.ibm.wala.classLoader.JarFileModule.getEntries(JarFileModule.java:66)
  at com.ibm.wala.classLoader.ClassLoaderImpl.getClassFiles(ClassLoaderImpl.java:157)
  at com.ibm.wala.classLoader.ClassLoaderImpl.init(ClassLoaderImpl.java:504)
  at com.ibm.wala.dalvik.classLoader.WDexClassLoaderImpl.init(WDexClassLoaderImpl.java:100)
  at com.ibm.wala.classLoader.ClassLoaderFactoryImpl.makeNewClassLoader(ClassLoaderFactoryImpl.java:115)
  at com.ibm.wala.classLoader.ClassLoaderFactoryImpl.getLoader(ClassLoaderFactoryImpl.java:69)
  at com.ibm.wala.ipa.cha.ClassHierarchy.<init>(ClassHierarchy.java:259)
  at com.ibm.wala.ipa.cha.ClassHierarchy.<init>(ClassHierarchy.java:201)
  at com.ibm.wala.ipa.cha.ClassHierarchyFactory.make(ClassHierarchyFactory.java:70)
  at com.ibm.wala.ipa.cha.ClassHierarchyFactory.make(ClassHierarchyFactory.java:59)
  at com.ibm.wala.ipa.cha.ClassHierarchyFactory.make(ClassHierarchyFactory.java:32)
  at de.infsec.tpl.LibraryIdentifier.createClassHierarchy(LibraryIdentifier.java:108)`

The reasons seems to be this try-with-resources construct with the creation of the JarFileModule in the body:
`try (final JarFile jar = new JarFile(new File(al))) {
   scope.addToScope(ClassLoaderReference.Primordial, new JarFileModule(jar));
}`

Moving the new JarFileModule into the try-block should fix this, however, this would require implementing AutoClosable for JarFileModule. This code was batch refactored in https://github.com/wala/WALA/commit/b1678882b399924b46a127c29143d223254969dc but it apparently hasn't been tested for side effects. A quick fix would be to revert it to the old, potentially leaking, implementation:

`scope.addToScope(ClassLoaderReference.Primordial, new JarFileModule(new JarFile(new File(al))));
`
While fixing this, maybe re-checking the aforementioned refactoring commit for other potential side-effects would be desired. Any suggestions on this?

**Comment by msridhar** [comment]
@liblit looks like you did the refactor.  Any thoughts here?

**Comment by liblit** [comment]
I agree with @reddr’s assessment that this was part of a batch refactor, and was not adequately tested. Rolling back this part of the change seems wise. If someone wants to review the rest of b1678882b399924b46a127c29143d223254969dc looking for similar problems, that is fine with me but unfortunately I cannot commit the time to doing that myself.

In the absence of such a systematic review, I recommend that we roll back only the change to the code that is giving @reddr trouble, rather than rolling back the entirety of b1678882b399924b46a127c29143d223254969dc. If other parts of that commit create problems for someone in the future, then those affected can report their problems as @reddr did here. Fortunately, as @reddr’s original report shows, this is not a silent failure: it throws an exception that is hard to miss.

#236 already documents the fact that `JarFile` instances leak. Reverting the problem that @reddr describes here would add one more potential leak to that existing set. Clearly that is better than preventing this code from working properly at all.

**Comment by msridhar** [comment]
@reddr can you open a PR that does the localized revert you suggested?
