### ISSUE TITLE
How to create CG from .jar file?

### ISSUE THREAD

**Issue by WaterWan** [wala/WALA#391]
My code(The complete vision is in issus20190114.zip/Demo2.java):
```java
		File exFile = new FileProvider().getFile("Java60RegressionExclusions.txt");

		AnalysisScope scope = AnalysisScopeReader.makeJavaBinaryAnalysisScope("primordial.jar", exFile);

		ClassHierarchy cha = ClassHierarchyFactory.make(scope);

		Iterable<Entrypoint> entrypoints = Util.makeMainEntrypoints(scope, cha);
		AnalysisOptions options = new AnalysisOptions(scope, entrypoints);
		options.setReflectionOptions(ReflectionOptions.NONE);
		CallGraphBuilder<InstanceKey> builder = Util.makeVanillaZeroOneCFABuilder(Language.JAVA, options,
				new AnalysisCacheImpl(), cha, scope);
		CallGraph cg = builder.makeCallGraph(options, null);
```

When it runs, it gives out error messages(The complete version in issue20190114.zip/logs.txt):
```
at com.ibm.wala.ipa.callgraph.propagation.PropagationCallGraphBuilder.makeCallGraph(PropagationCallGraphBuilder.java:261)
	at demo.Demo2.main(Demo2.java:54)

```
What can I do to make the code run successfully? Thank you!

[issue20190114.zip](https://github.com/wala/WALA/files/2755221/issue20190114.zip)

**Comment by Fan0429** [comment]
Hi , I have the same question with you . but I only know in your “Java60RegressionExclusions.txt” file you ignore some class . If you delete the lines in the txt ,you will see the probelms fewer than before. but .. there are still have some probelm in it like ,it cannot find the eclipse/swt class file.

**Comment by WaterWan** [comment]
I just use javapraser to finish my work:(
