### ISSUE TITLE
Cannot make call graph for Cassandra

### ISSUE THREAD

**Issue by SpectrumLi** [wala/WALA#423]
Hi,

I am trying to build the callgraph for latest Cassandra source code based on Wala but met an error.

CallGraphBuilder<InstanceKey> cgb = Util.makeZeroCFABuilder(options, new AnalysisCacheImpl(), cha, scope);
CallGraph cg = cgb.makeCallGraph(options, null);

I print the cha(ClassHierarchy) which is correctly loaded. 
I tried Wala-1.5.* and Wala-1.4.3. I also tried Cassandra-4.0,3.9,3.10 and 3.11. Java version is 1.8. All of them report the following error:
 Exception in thread "main" java.lang.NullPointerException
	at com.ibm.wala.ipa.summaries.LambdaSummaryClass.makeTrampoline(LambdaSummaryClass.java:274)
	at com.ibm.wala.ipa.summaries.LambdaSummaryClass.<init>(LambdaSummaryClass.java:71)
	at com.ibm.wala.ipa.summaries.LambdaSummaryClass.findOrCreate(LambdaSummaryClass.java:53)
	at com.ibm.wala.ipa.summaries.LambdaMethodTargetSelector.getCalleeTarget(LambdaMethodTargetSelector.java:65)
	at com.ibm.wala.ipa.summaries.BypassMethodTargetSelector.getCalleeTarget(BypassMethodTargetSelector.java:136)
	at com.ibm.wala.ipa.callgraph.propagation.PropagationCallGraphBuilder.getTargetForCall(PropagationCallGraphBuilder.java:717)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$1.apply(SSAPropagationCallGraphBuilder.java:2032)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$1.apply(SSAPropagationCallGraphBuilder.java:1)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$CrossProductRec.rec(SSAPropagationCallGraphBuilder.java:533)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.iterateCrossProduct(SSAPropagationCallGraphBuilder.java:2013)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.getTargetsForCall(SSAPropagationCallGraphBuilder.java:2038)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$ConstraintVisitor.visitInvokeInternal(SSAPropagationCallGraphBuilder.java:1143)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$ConstraintVisitor.visitInvoke(SSAPropagationCallGraphBuilder.java:1113)
	at com.ibm.wala.ssa.SSAInvokeInstruction.visit(SSAInvokeInstruction.java:87)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.addBlockInstructionConstraints(SSAPropagationCallGraphBuilder.java:291)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.addNodeInstructionConstraints(SSAPropagationCallGraphBuilder.java:261)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.unconditionallyAddConstraintsFromNode(SSAPropagationCallGraphBuilder.java:233)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.addConstraintsFromNode(SSAPropagationCallGraphBuilder.java:199)
	at com.ibm.wala.ipa.callgraph.propagation.PropagationCallGraphBuilder.addConstraintsFromNewNodes(PropagationCallGraphBuilder.java:337)
	at com.ibm.wala.ipa.callgraph.propagation.StandardSolver.solve(StandardSolver.java:58)
	at com.ibm.wala.ipa.callgraph.propagation.PropagationCallGraphBuilder.makeCallGraph(PropagationCallGraphBuilder.java:270)

Anyone know how to avoid this NPE problem? Thanks a lot!

**Comment by msridhar** [comment]
Thanks for the report!  Can you link a cassandra jar that repros the problem?  And how do you set up the entrypoints in the `AnalysisOptions` and the `AnalysisScope`?

**Comment by SpectrumLi** [comment]
Thanks for your reply!

The jar file is compiled from the latest source code https://github.com/apache/cassandra. 
Can I upload it here?  Getting the jar is quite easy: download the code and type "ant" to compile.

I add the entrypoints to analysisOption but not analysisScope. Here are more details about the code:

AnalysisScope scope = AnalysisScopeReader.makeJavaBinaryAnalysisScope(source,exfile);
ClassHierarchy cha = ClassHierarchyFactory.make(scope);
Iterable<Entrypoint> eps = Util.makeMainEntrypoints(scope, cha);
AnalysisOptions options = new AnalysisOptions(scope, eps);
CallGraphBuilder<InstanceKey> cgb = Util.makeZeroCFABuilder(options, new AnalysisCacheImpl(), cha, scope);
CallGraph cg = cgb.makeCallGraph(options, null);
System.out.println("CG is " + cg.getClass());

**Comment by SpectrumLi** [comment]
the jar name is apache-cassandra-4.0-SNAPSHOT.jar

**Comment by msridhar** [comment]
I repro'd with [this Cassandra release](https://search.maven.org/artifact/org.apache.cassandra/cassandra-all/3.11.4/jar).  The issue is we don't handle the case where a lambda refers to an unresolved method.  For me this occurred because I analyzed just with the cassandra.jar but not with its dependencies.  When I print warnings from building the class hierarchy I see:

```
7. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Application,Lorg/apache/cassandra/cql3/CqlParser> No superclass found for <Application,Lorg/apache/cassandra/cql3/CqlParser> Superclass name Lorg/antlr/runtime/Parser
```

So `CqlParser` doesn't get loaded, and a lambda reference to `< Application, Lorg/apache/cassandra/cql3/CqlParser, query()Lorg/apache/cassandra/cql3/statements/ParsedStatement; >` cannot be resolved.

(You can print warnings by doing this after ClassHierarchy is built:

```java
    System.out.println(Warnings.asString());
    Warnings.clear();
```
)

WALA should not NPE in this case; we will fix when we get time.  In the meantime, for this case it should be a workaround to add all relevant dependent library jars to the `AnalysisScope` (or at least add the right antlr jar).

**Comment by SpectrumLi** [comment]
Thanks so much for your suggestion! 
Finally, it works after adding more jars and excluding some classes.

**Comment by msridhar** [comment]
Ok, great.  We will eventually fix this NPE.  I do wonder if we should find
a better way API-wise to surface class hierarchy warnings to make these
kind of issues more evident.

--Manu

**Comment by coder-chenzhi** [comment]
@SpectrumLi Hi, Li. I am conducting static analysis (call graph analysis) on large-scale software systems (e.g. Cassandra) by WALA. But I am stuck in the OOM error. Can I know your machine configuration for running such large-scale analysis? Thanks!

**Comment by SpectrumLi** [comment]
@coder-chenzhi 
1. have you specified the java max memory argument when launching the program?
2. add more classes to the exclusive file so that the analysis won't go too deep.
3. what kind of analysis are you conducting? different analysis vary a lot.

**Comment by coder-chenzhi** [comment]
@SpectrumLi Thanks for your quick reply!  I intend to build the complete call graph of mediate-scale and large-scale software systems (100+ KLOC). And I have set the `-Xmx` parameter of JVM to 6GB due to the limit of my machine.

**Comment by SpectrumLi** [comment]
add more RAM to your machine. My feeling is cassandra requires more than 16G memory.

**Comment by coder-chenzhi** [comment]
@SpectrumLi Thanks for your advice! BTW, how do you figure out the proper entry points when you analyze software like Cassandra? Or you use the defaut `makeMainEntrypoints()` method, which will take all classes with `main` method as the entry points?

**Comment by Fan0429** [comment]
@SpectrumLi  Hi, Li . I am using WALA to conducting static analysis, but I met some problem. When I  buliding call graph,  some jars have these problem :

`Exception in thread "main" java.lang.IllegalStateException: Could not create a entrypoint callsites: 1. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Ljavafx/embed/swt/CustomTransfer> No superclass found for <Primordial,Ljavafx/embed/swt/CustomTransfer> Superclass name Lorg/eclipse/swt/dnd/ByteArrayTransfer
2. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Ljavafx/embed/swt/FXCanvas> No superclass found for <Primordial,Ljavafx/embed/swt/FXCanvas> Superclass name Lorg/eclipse/swt/widgets/Canvas
3. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Lorg/eclipse/swt/dnd/DragSourceListener
4. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Lorg/eclipse/swt/dnd/DropTargetListener
com.ibm.wala.ipa.callgraph.propagation.PropagationCallGraphBuilder.makeCallGraph(PropagationCallGraphBuilder.java:263)`

the wala seems cannot get the eclipse.swt package‘s .class file, and so I cannot build a Call Graph  to slice.
Did you meet any problems like this? This problem brother me for a long time. 
the problem Jar like this :
http://mirror.bit.edu.cn/apache/commons/io/binaries/
Thank you very much.
