### ISSUE TITLE
CAstWrapper exception caused at initialization

### ISSUE THREAD

**Issue by tiganov** [wala/WALA#508]
It appears that calling `initialize(env)` [here](https://github.com/wala/WALA/blob/master/com.ibm.wala.cast/source/c/jni/CAstWrapper.cpp#L69) is causing [us](https://github.com/themaplelab/swan/tree/structure-overhaul) an exception. 

We are running a Java program, then using JNI to call a shared library written in C++, which creates a `CAstWrapper` object, but it's initialization is causing an exception.

Removing that initialization call appears to solve the problem for us, but I am not sure if there are side effects to doing that.

**Edit:**
I modified the code a bit so reported line numbers are not original.
```
java.lang.RuntimeException: exception at /Users/tiganov/Documents/CS/swift-source/WALA/com.ibm.wala.cast/source/c/jni/CAstWrapper.cpp:73
        at ca.maple.swan.analysis.translator.SwiftToCAstTranslator.translateToCAstNodes(Native Method)
        at ca.maple.swan.analysis.drivers.MainAnalysisDriver.main(MainAnalysisDriver.java:39)
Caused by: java.lang.RuntimeException: exception at /Users/tiganov/Documents/CS/swift-source/WALA/com.ibm.wala.cast/source/c/jni/Java_com_ibm_wala_cast_ir_translator_NativeBridge.cpp:18
        ... 2 more
Caused by: java.lang.NoClassDefFoundError: com/ibm/wala/util/collections/HashSetFactory
        at com.ibm.wala.cast.tree.CAstQualifier.<clinit>(CAstQualifier.java:20)
        ... 2 more
Caused by: java.lang.ClassNotFoundException: com.ibm.wala.util.collections.HashSetFactory
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 3 more
```
Lines 17/18 of the `[…]NativeBridge.cpp`
```
jclass CAstQualifier = env->FindClass( "com/ibm/wala/cast/tree/CAstQualifier" );
  THROW_ANY_EXCEPTION(exp);
```

So it appears the exception occurs when loading the `CAstQualifier` class.

**Comment by tiganov** [comment]
Fixed: Wala util was not in path.
