### ISSUE TITLE
why can not analyze the source file(.java) dir of java programs

### ISSUE THREAD

**Issue by liberatorqjw** [wala/WALA#573]
hi:
 In the test code, it shows that wala can analyze when the input is java source file dir, 
```
   AnalysisScope scope = new JavaSourceAnalysisScope();
    // add standard libraries to scope
    String[] stdlibs = WalaProperties.getJ2SEJarFiles();
    for (String stdlib : stdlibs) {
      scope.addToScope(ClassLoaderReference.Primordial, new JarFile(stdlib));
    }
    
//    ExampleUtil.addDefaultExclusions(scope);	//
//    ExampleUtil.addTailExclusions(scope);	//
    
    // add the source directory
    scope.addToScope(JavaSourceAnalysisScope.SOURCE, new SourceDirectoryTreeModule(new File(sourceDir)));
   
```
but when i change the sourceDir is any java program, it can not analye more.
```
failed to load impl class com.ibm.wala.cast.java.translator.polyglot.PolyglotSourceLoaderImpl
```
or 
```
Exception in thread "main" java.lang.NullPointerException
	at com.ibm.wala.cast.java.translator.jdt.JDTJava2CAstTranslator.createClassDeclaration(JDTJava2CAstTranslator.java:466)
	at com.ibm.wala.cast.java.translator.jdt.JDTJava2CAstTranslator.visitTypeDecl(JDTJava2CAstTranslator.java:407)
	at com.ibm.wala.cast.java.translator.jdt.JDTJava2CAstTranslator.visit(JDTJava2CAstTranslator.java:2812)
	at com.ibm.wala.cast.java.translator.jdt.JDTJava2CAstTranslator.translateToCAst(JDTJava2CAstTranslator.java:258)
	at com.ibm.wala.cast.java.translator.jdt.ecj.ECJSourceModuleTranslator$ECJAstToIR.acceptAST(ECJSourceModuleTranslator.java:94)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:1035)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:633)
	at org.eclipse.jdt.core.dom.ASTParser.createASTs(ASTParser.java:995)
	at com.ibm.wala.cast.java.translator.jdt.ecj.ECJSourceModuleTranslator.loadAllSources(ECJSourceModuleTranslator.java:190)
	at com.ibm.wala.cast.java.loader.JavaSourceLoaderImpl.loadAllSources(JavaSourceLoaderImpl.java:502)
	at com.ibm.wala.classLoader.ClassLoaderImpl.init(ClassLoaderImpl.java:520)
	at com.ibm.wala.cast.java.loader.JavaSourceLoaderImpl.init(JavaSourceLoaderImpl.java:513)
	at com.ibm.wala.cast.java.translator.jdt.ecj.ECJClassLoaderFactory.makeNewClassLoader(ECJClassLoaderFactory.java:28)
	at com.ibm.wala.classLoader.ClassLoaderFactoryImpl.getLoader(ClassLoaderFactoryImpl.java:69)
	at com.ibm.wala.ipa.cha.ClassHierarchy.<init>(ClassHierarchy.java:259)
	at com.ibm.wala.ipa.cha.ClassHierarchy.<init>(ClassHierarchy.java:201)
	at com.ibm.wala.ipa.cha.ClassHierarchyFactory.make(ClassHierarchyFactory.java:70)
	at com.ibm.wala.ipa.cha.ClassHierarchyFactory.make(ClassHierarchyFactory.java:59)
	at com.ibm.wala.cast.java.ecj.util.SourceDirCallGraph.main(SourceDirCallGraph.java:92)
```
can someone tell me the solution? thanks.

**Comment by liberatorqjw** [comment]
I solve it。

**Comment by tuanngokien** [comment]
Hi @liberatorqjw , I just trying to analyze static java sources and I'm facing the same issue that you've mentioned in the first posted.  How you solved this? Thanks for notice.

**Comment by liberatorqjw** [comment]
@tuanngokien  i do as follows:

```java
AnalysisScope scope=new JavaSourceAnalysisScope();
        String[] stdLibs= WalaProperties.getJ2SEJarFiles();
        //String[] stdLibs=WalaProperties.J2EE_DIR("");
        for (String s:stdLibs
             ) {
            scope.addToScope(ClassLoaderReference.Primordial,new JarFile(s));
        }
        //scope.addToScope(ClassLoaderReference.Extension,new JarFile("/home/yuzzz/DeveloperTools/druid-1.1.10.jar"));

        //read jar file；
        String[] jarPath=getAllClass02.jarFileRead(sourceDirDepends);
        for(String path:jarPath){
            scope.addToScope(ClassLoaderReference.Application,new JarFile(path));
        }

        scope.addToScope(JavaSourceAnalysisScope.SOURCE, new SourceDirectoryTreeModule(new File(sourceDir)));
        System.out.println(scope.getModules(ClassLoaderReference.Application));
        IClassHierarchy cha= ClassHierarchyFactory.make(scope,new ECJClassLoaderFactory(scope.getExclusions()));
```

**Comment by dareenkf** [comment]
Hi @liberatorqjw , What is "getAllClass02" in your code?

**Comment by xxwxxwen** [comment]
@liberatorqjw how to get a jar file? I can only build call graph for a java file and could not build for a directory(with many java files). Does it  require to transform .java files into jar file? How to generate jar file? What is "getAllClass02.jarFileRead" mentioned above? 
How to makeEntrypoint for a class without main method? I met the same error.
Could you give me a reply at your convenience. Thanks a lot for your help!

**Comment by tuanngokien** [comment]
> 

Here is main part of the code that I used WALA to parse a Java project (multiple source code files).
This code is not runnable (since I showed you only relevant parts). 
You can follow the same steps to build your own parser. 

https://gist.github.com/tuanngokien/160c172fc9cc0ae7182ce8ae8a9c1a8b

**Comment by tuanngokien** [comment]
> @liberatorqjw how to get a jar file? I can only build call graph for a java file and could not build for a directory(with many java files). Does it require to transform .java files into jar file? How to generate jar file? What is "getAllClass02.jarFileRead" mentioned above? How to makeEntrypoint for a class without main method? I met the same error. Could you give me a reply at your convenience. Thanks a lot for your help!

Here is main part of the code that I used WALA to parse a Java project (multiple source code files).
This code is not runnable (since I showed you only relevant parts).
You can follow the same steps to build your own parser.

https://gist.github.com/tuanngokien/160c172fc9cc0ae7182ce8ae8a9c1a8b

**Comment by xxwxxwen** [comment]
@tuanngokien Thank you so much for your help!
