### ISSUE TITLE
com.ibm.wala.ipa.modref.ModRef$ModVisitor cannot be cast to com.ibm.wala.cast.java.ssa.AstJavaInstructionVisitor

### ISSUE THREAD

**Issue by liberatorqjw** [wala/WALA#578]
Hi:

I started working with Wala and successfully created a call graph and a pointer analysis from Java source.
Unfortunately was not able to create a slice from Java source. The example on the wiki from bytecode works.

Here is the code:

JavaSourceAnalysisEngine engine = new PolyglotJavaSourceAnalysisEngine();
String srcFilePath = "<My project path>";
File f = new File(srcFilePath);
engine.addSourceModule(new SourceDirectoryTreeModule(f));
engine.setExclusionsFile("<My Wala Path>" + CallGraphTestUtil.REGRESSION_EXCLUSIONS);

engine.buildAnalysisScope();
IClassHierarchy cha = engine.buildClassHierarchy();
CallGraph cg = engine.buildDefaultCallGraph();
PointerAnalysis pa = engine.getPointerAnalysis();

// findCallTo(...) from the example in the Wiki
Statement statement = findCallTo(findMainMethod(cg), "println");
Collection<Statement> slice;
slice = Slicer.computeBackwardSlice(statement, cg, pa);

When I execute the above code I get a  java.lang.ClassCastException. (Stack trace below)
Does anyone have an idea what I am doing wrong or can provide a working example for what I am trying to do?

java.lang.ClassCastException: com.ibm.wala.ipa.modref.ModRef$ModVisitor cannot be cast to com.ibm.wala.cast.java.ssa.AstJavaInstructionVisitor
	at com.ibm.wala.cast.java.ssa.AstJavaInvokeInstruction.visit(AstJavaInvokeInstruction.java:49)
	at com.ibm.wala.ipa.modref.ModRef.scanNodeForMod(ModRef.java:140)
	at com.ibm.wala.ipa.modref.ModRef.lambda$scanForMod$0(ModRef.java:106)
	at com.ibm.wala.ipa.callgraph.CallGraphTransitiveClosure.collectNodeResults(CallGraphTransitiveClosure.java:61)
	at com.ibm.wala.ipa.modref.ModRef.scanForMod(ModRef.java:105)
	at com.ibm.wala.ipa.modref.ModRef.computeMod(ModRef.java:63)
	at com.ibm.wala.ipa.slicer.SDG.<init>(SDG.java:137)
	at com.ibm.wala.ipa.slicer.SDG.<init>(SDG.java:119)
	at com.ibm.wala.ipa.slicer.Slicer.computeBackwardSlice(Slicer.java:176)
	at com.ibm.wala.ipa.slicer.Slicer.computeBackwardSlice(Slicer.java:281)
	at com.ibm.wala.examples.CreateSDGForJavaSource.SlicerTest(CreateSDGForJavaSource.java:179)
	at com.ibm.wala.examples.CreateSDGForJavaSource.CFGBuild(CreateSDGForJavaSource.java:158)
	at com.ibm.wala.examples.CreateSDGForJavaSource.CFGStart(CreateSDGForJavaSource.java:132)
	at com.ibm.wala.examples.CreateSDGForJavaSource.main(CreateSDGForJavaSource.java:101)

**Comment by msridhar** [comment]
What version of Java are you using?  `PolyglotJavaSourceAnalysisEngine` was removed long ago.  In any case I think the solution in the latest WALA is to use `AstJavaModRef`:

https://github.com/wala/WALA/blob/master/com.ibm.wala.cast.java/src/com/ibm/wala/cast/java/ipa/modref/AstJavaModRef.java

You might need to use a slightly different API to pass it to the slicer.

I'm going to close, but if you think there's a further bug please comment or re-open

**Comment by liberatorqjw** [comment]
ok, Thanks your help. I used the wrong version
