### ISSUE TITLE
java source data- flow

### ISSUE THREAD

**Issue by liberatorqjw** [wala/WALA#584]
Hi:
 I want　to use wala to analysis Java Source Program. and I want to use the data flow.
but when I use the demand point analysis as follows:
```
 CallGraphBuilder<InstanceKey> cgBuilder = findOrCreateBuilder(options, cha, scope, analysisCache, mainClassArray);
    CallGraph cg = cgBuilder.makeCallGraph(options, null);

     MemoryAccessMap mam = new SimpleMemoryAccessMap(cg,
     cgBuilder.getPointerAnalysis().getHeapModel(), true);
//    MemoryAccessMap mam = new PABasedMemoryAccessMap(cg, cgBuilder.getPointerAnalysis());
    SSAPropagationCallGraphBuilder builder = Util.makeVanillaZeroOneCFABuilder(Language.JAVA, options, analysisCache, cha, scope);
    DemandRefinementPointsTo fullDemandPointsTo = DemandRefinementPointsTo.makeWithDefaultFlowGraph(cg, builder, mam, cha, options,
        getStateMachineFactory());
//
//    // always refine array fields; otherwise, can be very sensitive to differences
//    // in library versions.  otherwise, no refinement by default
    fullDemandPointsTo.setRefinementPolicyFactory(new SinglePassRefinementPolicy.Factory(new OnlyArraysPolicy(), new NeverRefineCGPolicy()));
    return fullDemandPointsTo;
```
i occured the error:
｀｀｀
java.lang.ClassCastException: com.ibm.wala.demandpa.util.SimpleMemoryAccessMap$SSAMemoryAccessVisitor cannot be cast to com.ibm.wala.cast.java.ssa.AstJavaInstructionVisitor

	at com.ibm.wala.cast.java.ssa.AstJavaInvokeInstruction.visit(AstJavaInvokeInstruction.java:49)
	at com.ibm.wala.demandpa.util.SimpleMemoryAccessMap.populate(SimpleMemoryAccessMap.java:111)
	at com.ibm.wala.demandpa.util.SimpleMemoryAccessMap.populate(SimpleMemoryAccessMap.java:89)
	at com.ibm.wala.demandpa.util.SimpleMemoryAccessMap.<init>(SimpleMemoryAccessMap.java:84)
	at com.ibm.wala.examples.examples.demandpa.AbstractPtrTest.makeDemandPointerAnalysis(AbstractPtrTest.java:261)
	at com.ibm.wala.examples.examples.demandpa.AbstractPtrTest.getPointsToSetToTest(AbstractPtrTest.java:220)
	at com.ibm.wala.examples.examples.demandpa.AbstractPtrTest.doPointsToSizeTest(AbstractPtrTest.java:208)
	at com.ibm.wala.examples.examples.demandpa.IntraprocTest.testId(IntraprocTest.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
｀｀｀
Does the Wala support the Java source to use demand pointer
Or
How can i use the data-flow to analysis Java Source program.
Thanks.

**Comment by msridhar** [comment]
The demand pointer analysis only supports bytecode at the moment, not source code. It shouldn’t be very hard to extend, but it would take some work. Standard points to analyses should work fine with Java source. Do you need an example of that?

**Comment by msridhar** [comment]
Actually, from your `CallGraphBuilder` you can call `getPointerAnalysis` to get the pointer analysis result, which hopefully contains what you need

**Comment by liberatorqjw** [comment]
Yes, I can get the getPointerAnalysis(). Oh, If I want to make demand pointer support  the source， , can you guide me which function is extended?

**Comment by liberatorqjw** [comment]
If I want to get a dataflow for a variable for Java Source, can you provide an example of that ?
Thanks

**Comment by msridhar** [comment]
> Yes, I can get the getPointerAnalysis(). Oh, If I want to make demand pointer support the source， , can you guide me which function is extended?

Thinking more, this won't be completely easy.  The issue with the source frontend is that it includes IR instructions for accessing variables from enclosing lexical scopes (like accessing a final local variable from the enclosing method inside an anonymous class).  All such accesses get translated into field accesses at the bytecode level.  Handling these at the source level takes some care in order to preserve context sensitivity and not just jump around the call graph.

Bottom line if you really need the functionality, I can try to help.  But I think it would be much easier to just use the bytecode front end.  Is there some reason you need to use the Java source front end?

> If I want to get a dataflow for a variable for Java Source, can you provide an example of that ?
Thanks

Here is the documentation for the bytecode front end:

https://github.com/wala/WALA/wiki/Mapping-to-source-code

That's for mapping IR variables back to source code variables.  A particular source variable can map to many SSA variables, or to 0 in some cases.  I think your best bet for mapping from a source variable to IR variables is to call `getLocalMap()` on the IR, iterate through each SSA value number, and construct the mapping that way.

**Comment by liberatorqjw** [comment]
oh, Thanks ,I will try it.
