### ISSUE TITLE
Some question about "instructionIndex" and "bcIndex".

### ISSUE THREAD

**Issue by QRXqrx** [wala/WALA#632]
Hi,

I'm learning to use `Slicer` these days, and I bumped into several question yesterday. Here are some questions I want to ask:
1. How to determine the slice point? I've read some literature about slicing, it seems one need a target point to run a slicing process. But I have noticed that `Slicer` use a abstract `Instruction` as a slicing point(If I'm not wrong), so how can I transform point from visible source code to an abstract `Instruction`?
2. There is a parameter `instructionIndex` needed for initialize a `NormalStatement`, where to get it? I saw loops/traverse in slice examples, but what if I only have one point to slice?
3. There is a parameter `bcIndex` needed for `IMethod.getLineNumber(int bcIndex)`. Where to get it? And how do I know whether it will cause "ArrayIndexOutOfBoundsException"?

What's more, I encountered a strange Exception in my practice:
```
java.lang.ArrayIndexOutOfBoundsException: 9

	at com.ibm.wala.ipa.slicer.StatementWithInstructionIndex.getInstruction(StatementWithInstructionIndex.java:34)
	at SimpleTest.test2(SimpleTest.java:175)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

Here's my code snippet:
```
        for(CGNode node : callGraph) {
            if(!node.toString().contains("Application")) {
                continue;
            }
            IMethod method = node.getMethod();
            System.out.println("Method Class: " + method.getClass());
            System.out.println("Node" + node.getGraphNodeId() + " :" + method);
            Statement seed = new NormalStatement(node, method.getLineNumber(0));
            System.out.println(((NormalStatement) seed).getInstruction());
        }
```

And here the source code of WALA:
```
  private final int instructionIndex;

  protected StatementWithInstructionIndex(CGNode node, int instructionIndex) {
    super(node);
    this.instructionIndex = instructionIndex;
  }

  public int getInstructionIndex() {
    return instructionIndex;
  }

  public SSAInstruction getInstruction() {
    return getNode().getIR().getInstructions()[instructionIndex];
  }
```
It seems `indexInstruction` is `private`, so I'm puzzled about how this error happens! By the way, I'm using 1.5.3 in this practice.
Please reply me at your convenience, thanks a lot :-)

**Comment by msridhar** [comment]
Hi @QRXqrx, I'd suggest reading these documentation pages to start:

WALA IR: https://github.com/wala/WALA/wiki/Intermediate-Representation-(IR)
Slicer: https://github.com/wala/WALA/wiki/Slicer
Mapping to source code: https://github.com/wala/WALA/wiki/Mapping-to-source-code

Also you often want to slice to / from a call site.  This logic gives an example of how to find a call site invoking a method:

https://github.com/wala/WALA/blob/master/com.ibm.wala.core/src/com/ibm/wala/ipa/slicer/SlicerUtil.java#L38

Re: the array index issue, that's because `getInstructions()` returns the underlying instruction array, which gets accessed by `[instructionIndex]`.  If you set up the statement with an invalid `instructionIndex` then `getInstruction()` will fail.

For a `NormalStatement` the instruction index should be the one of the corresponding IR instruction.  You'll probably need to iterate through the IR instructions to find the one that you want.

I hope that helps; let us know if you have more questions.

**Comment by QRXqrx** [comment]
Thanks for your reply, I have learned code logic of `doSlicing` from here: [http://wala.sourceforge.net/wiki/index.php/UserGuide:Slicer](url) these days. I think what you answered above help me understand these code further. This issue will be closed,  and I will keep going studying the materials you gave. I'll open new issues if I have new questions again, thanks a lot. :-)
