### ISSUE TITLE
Failed lexical access during callgraph construction when method variable is referenced by anonymous class method

### ISSUE THREAD

**Issue by mattkindy-praetorian** [wala/WALA#668]
I encounter the following error when using CAst to attempt to translate `FailedLexicalAccessCase` (below)
```
com.ibm.wala.util.debug.UnimplementedError
	at com.ibm.wala.util.debug.Assertions.UNREACHABLE(Assertions.java:46)
	at com.ibm.wala.cast.ipa.callgraph.AstSSAPropagationCallGraphBuilder$AstConstraintVisitor.addUpwardFunargConstraints(AstSSAPropagationCallGraphBuilder.java:814)
	at com.ibm.wala.cast.ipa.callgraph.AstSSAPropagationCallGraphBuilder$AstConstraintVisitor.handleRootLexicalReference(AstSSAPropagationCallGraphBuilder.java:861)
	at com.ibm.wala.cast.ipa.callgraph.AstSSAPropagationCallGraphBuilder$AstConstraintVisitor.access$2600(AstSSAPropagationCallGraphBuilder.java:350)
	at com.ibm.wala.cast.ipa.callgraph.AstSSAPropagationCallGraphBuilder$AstConstraintVisitor$LexicalOperator.doLexicalPointerKeys(AstSSAPropagationCallGraphBuilder.java:668)
	at com.ibm.wala.cast.ipa.callgraph.AstSSAPropagationCallGraphBuilder$AstConstraintVisitor$LexicalOperator.access$500(AstSSAPropagationCallGraphBuilder.java:632)
	at com.ibm.wala.cast.ipa.callgraph.AstSSAPropagationCallGraphBuilder$AstConstraintVisitor.visitLexical(AstSSAPropagationCallGraphBuilder.java:378)
	at com.ibm.wala.cast.ipa.callgraph.AstSSAPropagationCallGraphBuilder$AstConstraintVisitor.visitAstLexicalWrite(AstSSAPropagationCallGraphBuilder.java:451)
	at com.ibm.wala.cast.ir.ssa.AstLexicalWrite.visit(AstLexicalWrite.java:98)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.addBlockInstructionConstraints(SSAPropagationCallGraphBuilder.java:272)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.addNodeInstructionConstraints(SSAPropagationCallGraphBuilder.java:249)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.unconditionallyAddConstraintsFromNode(SSAPropagationCallGraphBuilder.java:225)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.addConstraintsFromNode(SSAPropagationCallGraphBuilder.java:190)
	at com.ibm.wala.ipa.callgraph.propagation.PropagationCallGraphBuilder.addConstraintsFromNewNodes(PropagationCallGraphBuilder.java:311)
	at com.ibm.wala.ipa.callgraph.propagation.StandardSolver.solve(StandardSolver.java:56)
	at com.ibm.wala.ipa.callgraph.propagation.PropagationCallGraphBuilder.makeCallGraph(PropagationCallGraphBuilder.java:251)
```

**`FailedLexicalAccessCase`**
```java
package source_code_for_testing.encountered_errors.failed_lexical_access;

public class FailedLexicalAccessCase {

  public void run(final String var) {
    new Object() {
      @Override
      public int hashCode() {

        try { }
        catch (Exception e) {
          System.out.println(var);
        }

        return 0;
      }
    };
  }

}
```

For reference, I'm using the following engine definition
```java
new JavaSourceAnalysisEngine() {
      @Override
      protected ClassLoaderFactory getClassLoaderFactory(SetOfClasses exclusions) {
        return new ECJClassLoaderFactory(exclusions);
      }

      @Override
      protected Iterable<Entrypoint> makeDefaultEntrypoints(@NonNull final AnalysisScope scope,
                                                            final IClassHierarchy cha) {
        return new AllSourceEntrypoints(cha);
      }
}
```

There is something wrong happening during translation in `AstTranslator`. By the time the callgraph gets to the lexical write that the method performs for variables in its signature, there are no exposed names for the method's `CGNode`. I believe this is because in `AstTranslator#doPrologue`, the method parameters are written as lexical writes 
```java
if (exposedNames.contains(arg)) {
  final Scope currentScope = context.currentScope();
  Symbol symbol = currentScope.lookup(arg);
  assert symbol.getDefiningScope() == currentScope;
  int argVN = symbol.valueNumber();
  CAstType type =
      (entity.getType() instanceof CAstType.Method)
          ? (CAstType) ((CAstType.Method) entity.getType()).getArgumentTypes().get(i)
          : topType();
  Access A = new Access(arg, context.getEntityName(entity), makeType(type), argVN);
  context.cfg().addInstruction(new AstLexicalWrite(context.cfg().currentInstruction, A));
}
```
but the parameters are not marked as exposed in nested scopes. I changed the above to
```java
if (exposedNames.contains(arg)) {
  final Scope currentScope = context.currentScope();
  Symbol symbol = currentScope.lookup(arg);
  assert symbol.getDefiningScope() == currentScope;
  int argVN = symbol.valueNumber();
  CAstType type =
      (entity.getType() instanceof CAstType.Method)
          ? (CAstType) ((CAstType.Method) entity.getType()).getArgumentTypes().get(i)
          : topType();
  Access A = new Access(arg, context.getEntityName(entity), makeType(type), argVN);
  context.cfg().addInstruction(new AstLexicalWrite(context.cfg().currentInstruction, A));
          
  addExposedName(entity, entity, arg, argVN, true, context);
}
```
and it seemed to resolve the issue

**Comment by msridhar** [comment]
@mattkindy-praetorian your fix looks reasonable to me.  Any chance you can open a PR with your fix and test case?  You can just add the test code somewhere in here:

https://github.com/wala/WALA/tree/master/com.ibm.wala.cast.java.test.data/src/test/java

**Comment by mattkindy-praetorian** [comment]
Sure thing
