### ISSUE TITLE
I'm getting the error when doing slicer

### ISSUE THREAD

**Issue by 161250029** [wala/WALA#684]
I'm getting this error.
```
Exception in thread "main" java.lang.NullPointerException
	at com.ibm.wala.ipa.slicer.NormalStatement.toString(NormalStatement.java:30)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at com.ibm.wala.dataflow.IFDS.TabulationSolver.propagate(TabulationSolver.java:754)
	at com.ibm.wala.dataflow.IFDS.PartiallyBalancedTabulationSolver.propagate(PartiallyBalancedTabulationSolver.java:46)
	at com.ibm.wala.dataflow.IFDS.TabulationSolver.addSeed(TabulationSolver.java:213)
	at com.ibm.wala.dataflow.IFDS.PartiallyBalancedTabulationSolver.addSeed(PartiallyBalancedTabulationSolver.java:84)
	at com.ibm.wala.dataflow.IFDS.TabulationSolver.initialize(TabulationSolver.java:204)
	at com.ibm.wala.dataflow.IFDS.TabulationSolver.solve(TabulationSolver.java:190)
	at com.ibm.wala.ipa.slicer.Slicer.slice(Slicer.java:254)
	at com.ibm.wala.ipa.slicer.Slicer.slice(Slicer.java:231)
	at com.ibm.wala.ipa.slicer.Slicer.computeSlice(Slicer.java:218)
	at com.ibm.wala.ipa.slicer.Slicer.computeBackwardSlice(Slicer.java:175)
	at ProgramSlicer.doSlicing(ProgramSlicer.java:81)
	at ProgramSlicer.main(ProgramSlicer.java:134)

Process finished with exit code 1
```
My code is following with annotations:
```java
import Tools.StmtFormater;
import com.ibm.wala.classLoader.IBytecodeMethod;
import com.ibm.wala.classLoader.Language;
import com.ibm.wala.ipa.callgraph.*;
import com.ibm.wala.ipa.callgraph.impl.Util;
import com.ibm.wala.ipa.callgraph.propagation.InstanceKey;
import com.ibm.wala.ipa.callgraph.propagation.PointerAnalysis;
import com.ibm.wala.ipa.cha.ClassHierarchy;
import com.ibm.wala.ipa.cha.ClassHierarchyFactory;
import com.ibm.wala.ipa.modref.ModRef;
import com.ibm.wala.ipa.slicer.NormalStatement;
import com.ibm.wala.ipa.slicer.SDG;
import com.ibm.wala.ipa.slicer.Slicer;
import com.ibm.wala.ipa.slicer.Statement;
import com.ibm.wala.shrikeCT.InvalidClassFileException;
import com.ibm.wala.ssa.IR;
import com.ibm.wala.util.CancelException;
import com.ibm.wala.util.WalaException;
import com.ibm.wala.util.config.AnalysisScopeReader;
import com.ibm.wala.util.config.FileOfClasses;
import com.ibm.wala.util.debug.Assertions;
import com.ibm.wala.util.graph.Graph;
import com.ibm.wala.util.graph.GraphSlicer;
import com.ibm.wala.util.strings.Atom;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.util.Collection;
import java.util.Iterator;
import java.util.function.Predicate;

public class ProgramSlicer {
    private static final String EXCLUSIONS =
            "java\\/awt\\/.*\n"
                    + "javax\\/swing\\/.*\n"
                    + "sun\\/awt\\/.*\n"
                    + "sun\\/swing\\/.*\n"
                    + "com\\/sun\\/.*\n"
                    + "sun\\/.*\n"
                    + "org\\/netbeans\\/.*\n"
                    + "org\\/openide\\/.*\n"
                    + "com\\/ibm\\/crypto\\/.*\n"
                    + "com\\/ibm\\/security\\/.*\n"
                    + "org\\/apache\\/xerces\\/.*\n"
                    + "java\\/security\\/.*\n"
                    + "";
    public static CallGraphBuilder doSlicing(String appJar) throws WalaException, CancelException, IOException, InvalidClassFileException {
        // create an analysis scope representing the appJar as a J2SE application
        AnalysisScope scope = AnalysisScopeReader.makeJavaBinaryAnalysisScope(appJar,null);
//        AnalysisScopeReader.readJavaScope(appJar , null , slicer.class.getClassLoader());
        scope.setExclusions(new FileOfClasses(new ByteArrayInputStream(EXCLUSIONS.getBytes("UTF-8"))));
        //官网示例代码写错
        ClassHierarchy cha = ClassHierarchyFactory.make(scope);

        Iterable<Entrypoint> entrypoints = com.ibm.wala.ipa.callgraph.impl.Util.makeMainEntrypoints(scope, cha);
        AnalysisOptions options = new AnalysisOptions(scope, entrypoints);

        // build the call graph
        //参数缺失且存在类型错误

        com.ibm.wala.ipa.callgraph.CallGraphBuilder cgb = Util.makeZeroCFABuilder(Language.JAVA ,options, new AnalysisCacheImpl(),cha, scope, null, null);

        //少一个参数
        CallGraph cg = cgb.makeCallGraph(options , null);

        PointerAnalysis pa = cgb.getPointerAnalysis();

        Statement statement = findSeedStatementByLineNumber(findMainMethod(cg , "goodG2B1" , "CWE15_External_Control_of_System_or_Configuration_Setting__connect_tcp_02"), 166);

        Collection<Statement> slice;

        // context-sensitive traditional slice
        ModRef<InstanceKey> modRef = ModRef.make();
        SDG<?> sdg = new SDG<>(cg, pa, modRef, Slicer.DataDependenceOptions.REFLECTION, Slicer.ControlDependenceOptions.NO_EXCEPTIONAL_EDGES, null);
        System.out.println("开始进行切片");

//        // context-sensitive thin slice

        slice = Slicer.computeBackwardSlice(statement, cg, pa, Slicer.DataDependenceOptions.NO_BASE_PTRS,
                Slicer.ControlDependenceOptions.NONE);
        System.out.println("结束切片");
        dumpSlice(slice);

        SDG<InstanceKey> sd=new SDG<InstanceKey>(cg, pa, Slicer.DataDependenceOptions.NO_BASE_NO_HEAP , Slicer.ControlDependenceOptions.FULL);

        // filter primordial stmt
        System.out.println("剪枝");
        Predicate<Statement> filter = o -> slice.contains(o) && !o.toString().contains("Primordial") && o.getKind() == Statement.Kind.NORMAL;
        Graph<Statement> graph = GraphSlicer.prune(sdg, filter);
        for (Statement s : graph)
            System.out.println(StmtFormater.format(s));
        return null;
    }

    //find the method where the seed statement is included.
    public static CGNode findMainMethod(CallGraph cg , String methodName , String className) {
        Atom name = Atom.findOrCreateUnicodeAtom(methodName);
        for (Iterator<? extends CGNode> it = cg.iterator(); it.hasNext();) {
            CGNode n = it.next();
            if (n.getMethod().getName().equals(name)  && n.getMethod().getDeclaringClass().getName().toString().equals("Ltestcases/CWE15_External_Control_of_System_or_Configuration_Setting/" + className)) {
                System.out.println(n.getMethod().getDeclaringClass().getName().toString() + " " + n.getMethod().getName().toString());
                return n;
            }
        }
        Assertions.UNREACHABLE("failed to find " + methodName +" method");
        return null;
    }
    
    //According to LineNumber , find the seed statement
    public static Statement findSeedStatementByLineNumber(CGNode n, int LineNumber) throws InvalidClassFileException {
        IR ir = n.getIR();
        for (int i = 0 ; i < ir.getInstructions().length ; i ++) {
            System.out.println(IRIdexToLineNumber(ir , i));
            if (IRIdexToLineNumber(ir , i) == LineNumber) {
                return new NormalStatement(n , i);
            }
        }
        Assertions.UNREACHABLE("failed to find call to "  + " in " + n);
        return null;
    }

    //IRindex to LineNumber
    public static int IRIdexToLineNumber(IR ir ,int instructionIndex) throws InvalidClassFileException {
        IBytecodeMethod method = (IBytecodeMethod)ir.getMethod();
        int bytecodeIndex = method.getBytecodeIndex(instructionIndex);
        int sourceLineNum = method.getLineNumber(bytecodeIndex);
        return sourceLineNum;
    }

    public static void dumpSlice(Collection<Statement> slice) {
        for (Statement s : slice) {
            System.out.println(s);
        }
    }
    public static void main(String[] args) throws IOException, WalaException, CancelException, InvalidClassFileException {
        doSlicing("src\\main\\java\\CWE15_External_Control_of_System_or_Configuration_Setting.jar");
    }
}
```
The code I encode is meant to do slicer according to LineNumber. As I get the seed statement , Doing slicer will cause a NullPointerException.

**Comment by msridhar** [comment]
So there are a couple issues here, particularly in this code:

```java
    //According to LineNumber , find the seed statement
    public static Statement findSeedStatementByLineNumber(CGNode n, int LineNumber) throws InvalidClassFileException {
        IR ir = n.getIR();
        for (int i = 0 ; i < ir.getInstructions().length ; i ++) {
            System.out.println(IRIdexToLineNumber(ir , i));
            if (IRIdexToLineNumber(ir , i) == LineNumber) {
                return new NormalStatement(n , i);
            }
        }
        Assertions.UNREACHABLE("failed to find call to "  + " in " + n);
        return null;
    }
```

1. A single source line may map to many IR instructions.  This code will choose the first match arbitrarily.  You probably want to check that it is at least the right type of instruction, based on whatever you are expecting from the source code.
2. The WALA IR instruction array can contain null entries, mostly due to historical reasons.  I am guessing that's what is happening here; `i` is the index of a `null` instruction.  So at the least, you should check that `ir.getInstructions()[i] != null`.

**Comment by 161250029** [comment]
I modify my code by adding a judgement that checks ir.getInstructions()[i] != null so that it runs well.
However, I happen to find that a single soure line may not map to a IR instrcution.This is my first question.I want to confirm it.The second question is based on your first suggestion.How can we judge the type of an instruction.Besides, you say a single source line may map to many IR instructions so we should choose which instructions to do slicer if not only one instruction not null.

**Comment by 161250029** [comment]
Can you give me a reply to the questions for further implement as I mentioned 8 days ago. It is really urgent for me.

**Comment by msridhar** [comment]
@161250029 sorry for the delay.  

> However, I happen to find that a single soure line may not map to a IR instrcution.This is my first question.I want to confirm it.

Yes, this is possible.  In particular, WALA does full copy propagation during conversion to SSA, and does not represent an assignment of a constant to an IR variable with an instruction.  So a Java source statement like `int x = 3;` will not have a corresponding IR instruction.

> The second question is based on your first suggestion.How can we judge the type of an instruction.Besides, you say a single source line may map to many IR instructions so we should choose which instructions to do slicer if not only one instruction not null.

This depends on what exactly it is you are trying to do.  E.g., if you know that your slice seed should be a call to a particular method, you should look for a corresponding invoke instruction for that line.  If you provide more details we can give another suggestion.

**Comment by 161250029** [comment]
```
         Connection dbConnection = null;
            dbConnection = IO.getDBConnection();
            /* POTENTIAL FLAW: Set the catalog name with the value of data
             * allowing a nonexistent catalog name or unauthorized access to a portion of the DB */
            dbConnection.setCatalog(data);
```
Given the above piece of code and  dbConnection.setCatalog(data) is the seed statement, as you say, the statement 'Connection dbConnection = null' does not exist in the Collection<Statement> after doing slicer.However , if the statement is not included, for one thing, I will not generate a compilable file， for the other thing，based on stain propagation principle, this statement is the 
pollution source.So how can I trace back to the assignment statement.

**Comment by msridhar** [comment]
Hi @161250029, yes, this is a known issue, see also here in the slicer docs:

https://github.com/wala/WALA/wiki/Slicer#warning-exclusion-of-copy-statements-from-slice

Unfortunately WALA does not have a good solution for producing executable slices.  WALA's slicer will get you all the relevant IR instructions, but you will have to add your own logic to pull in the relevant source statements.  It is possible the Java source front-end has a better story on finding relevant copy statements.  @juliandolby do you know?

**Comment by 161250029** [comment]
Because I can not  provide more details about the code corresponding to the source code line number，so I get all the IRs which map to the  source code line number to do slicer.However ，it often causes Endless loop when using backwardslice to do slicer. I want to know how to dos slicer without causing endless loop.

**Comment by msridhar** [comment]
I doubt it's an endless loop, just the slicer not scaling.  For scalability tips see here:

https://github.com/wala/WALA/wiki/Slicer#performance-tips

I'm going to close this issue as the discussion has diverged from the original question.  If you have another problem please open a new issue.
