### ISSUE TITLE
Thin slicer throws java.lang.ClassCastException: com.ibm.wala.ipa.modref.ModRef$ModVisitor cannot be cast to com.ibm.wala.cast.java.ssa.AstJavaInstructionVisitor 

### ISSUE THREAD

**Issue by ufarooq** [wala/WALA#696]
Thin Slicer throws ClassCastException when I try to run it for source code. I am sharing the stack trace below, driver and input code is posted [here](https://gist.github.com/ufarooq/6c9937fbdc20706a749c2b556cf52482).  
Here are a few notes:
* It works just fine when I am analyzing byte code. 
* Also, the context-sensitive traditional slicer is working fine for both Java and byte code. 

Stack Trace: 
``` 
Exception in thread "main" java.lang.ClassCastException: com.ibm.wala.ipa.modref.ModRef$ModVisitor cannot be cast to com.ibm.wala.cast.java.ssa.AstJavaInstructionVisitor
	at com.ibm.wala.cast.java.ssa.AstJavaInvokeInstruction.visit(AstJavaInvokeInstruction.java:49)
	at com.ibm.wala.ipa.modref.ModRef.scanNodeForMod(ModRef.java:140)
	at com.ibm.wala.ipa.modref.ModRef.lambda$scanForMod$0(ModRef.java:106)
	at com.ibm.wala.ipa.callgraph.CallGraphTransitiveClosure.collectNodeResults(CallGraphTransitiveClosure.java:61)
	at com.ibm.wala.ipa.modref.ModRef.scanForMod(ModRef.java:105)
	at com.ibm.wala.ipa.modref.ModRef.computeMod(ModRef.java:63)
	at com.ibm.wala.ipa.slicer.SDG.<init>(SDG.java:137)
	at com.ibm.wala.ipa.slicer.SDG.<init>(SDG.java:119)
	at com.ibm.wala.ipa.slicer.Slicer.computeBackwardSlice(Slicer.java:176)
	at android.wala.test.AnalyzeJava.main(AnalyzeJava.java:94)
```

**Comment by msridhar** [comment]
@ufarooq the CIThinSlicer should work now. For context sensitive thin slicing you can see the new test I added in #697 to see how to do it. You need to construct the `SDG` with the right `AstJavaModRef` object
