### ISSUE TITLE
How to choose a slice way whether forwardslice or backwardslice

### ISSUE THREAD

**Issue by 161250029** [wala/WALA#716]
As I use the Slicer Class to do slicer, I find that for some statement , if I choose computeBackwardSlice method , It will cause endless loop, if I choose computeForwardSlice method , It will run well，vice versa.So I want to know How to choose a slice way whether forwardslice or backwardslice.The exception is following:
```
java.lang.OutOfMemoryError: Java heap space

	at java.util.HashMap.resize(HashMap.java:704)
	at java.util.HashMap.putVal(HashMap.java:663)
	at java.util.HashMap.put(HashMap.java:612)
	at com.ibm.wala.util.intset.MutableMapping.add(MutableMapping.java:100)
	at com.ibm.wala.util.graph.impl.SlowNumberedNodeManager.addNode(SlowNumberedNodeManager.java:69)
	at com.ibm.wala.util.graph.AbstractGraph.addNode(AbstractGraph.java:96)
	at com.ibm.wala.ipa.slicer.PDG.addParamPassingStatements(PDG.java:1044)
	at com.ibm.wala.ipa.slicer.PDG.createNormalStatements(PDG.java:1001)
	at com.ibm.wala.ipa.slicer.PDG.createNodes(PDG.java:905)
	at com.ibm.wala.ipa.slicer.PDG.populate(PDG.java:192)
	at com.ibm.wala.ipa.slicer.PDG.getNumber(PDG.java:1270)
	at com.ibm.wala.ipa.slicer.SDGSupergraph.getLocalBlockNumber(SDGSupergraph.java:147)
	at com.ibm.wala.ipa.slicer.SDGSupergraph.getLocalBlockNumber(SDGSupergraph.java:26)
	at com.ibm.wala.dataflow.IFDS.BackwardsSupergraph.getLocalBlockNumber(BackwardsSupergraph.java:334)
	at com.ibm.wala.dataflow.IFDS.TabulationSolver.processParticularCallee(TabulationSolver.java:622)
	at com.ibm.wala.dataflow.IFDS.TabulationSolver.processCall(TabulationSolver.java:525)
	at com.ibm.wala.dataflow.IFDS.TabulationSolver.forwardTabulateSLRPs(TabulationSolver.java:253)
	at com.ibm.wala.dataflow.IFDS.TabulationSolver.solve(TabulationSolver.java:191)
	at com.ibm.wala.ipa.slicer.Slicer.slice(Slicer.java:254)
	at com.ibm.wala.ipa.slicer.Slicer.slice(Slicer.java:231)
	at com.ibm.wala.ipa.slicer.Slicer.computeSlice(Slicer.java:218)
	at com.ibm.wala.ipa.slicer.Slicer.computeBackwardSlice(Slicer.java:175)
	at com.example.demo.Tool.WalaSlicerTool.doSlicing(WalaSlicerTool.java:78)
	at com.example.demo.Service.DoSlicerServiceImpl.WalaSlicer_Positive(DoSlicerServiceImpl.java:34)
	at com.example.demo.test.DoSlicer.test2(DoSlicer.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
```

**Comment by msridhar** [comment]
Hi there, the running time of the slicer will depend on the size of the slice, which relates to the number of (transitive) control and data dependencies.  In your case, for your seed statement _s_, it seems that very few statements depend on the results of _s_, but _s_ depends on the results of many other statements.

In general, whether you do forward or backward slicing depends on the problem you are trying to solve.  You usually can't just choose forward vs. backward to improve performance.

Hope that helps!  Will close, but re-open if you have a follow-up.
