### ISSUE TITLE
Using ControlDependenceOptions.NO_EXCEPTIONAL_EDGES results in  java.lang.NullPointerException

### ISSUE THREAD

**Issue by Ido-Efrati** [wala/WALA#82]
Exception in thread "main" java.lang.NullPointerException
	at com.ibm.wala.util.graph.dominators.DominanceFrontiers.getDominanceFrontier(DominanceFrontiers.java:50)
	at com.ibm.wala.cfg.cdg.ControlDependenceGraph.buildControlDependence(ControlDependenceGraph.java:77)
	at com.ibm.wala.cfg.cdg.ControlDependenceGraph.<init>(ControlDependenceGraph.java:231)
	at com.ibm.wala.cfg.cdg.ControlDependenceGraph.<init>(ControlDependenceGraph.java:238)
	at com.ibm.wala.ipa.slicer.PDG.createControlDependenceEdges(PDG.java:248)
	at com.ibm.wala.ipa.slicer.PDG.createScalarEdges(PDG.java:186)
	at com.ibm.wala.ipa.slicer.PDG.populate(PDG.java:180)
	at com.ibm.wala.ipa.slicer.PDG.getNumber(PDG.java:1240)
	at com.ibm.wala.ipa.slicer.SDGSupergraph.getLocalBlockNumber(SDGSupergraph.java:154)
	at com.ibm.wala.ipa.slicer.SDGSupergraph.getLocalBlockNumber(SDGSupergraph.java:1)
	at com.ibm.wala.dataflow.IFDS.TabulationSolver.processParticularCallee(TabulationSolver.java:646)
	at com.ibm.wala.dataflow.IFDS.TabulationSolver.processCall(TabulationSolver.java:554)
	at com.ibm.wala.dataflow.IFDS.TabulationSolver.forwardTabulateSLRPs(TabulationSolver.java:279)
	at com.ibm.wala.dataflow.IFDS.TabulationSolver.solve(TabulationSolver.java:206)
	at com.ibm.wala.ipa.slicer.Slicer.slice(Slicer.java:205)
	at com.ibm.wala.ipa.slicer.Slicer.computeSlice(Slicer.java:184)
	at com.ibm.wala.ipa.slicer.Slicer.computeForwardSlice(Slicer.java:145)

**Comment by herda** [comment]
I also get this exception when the program I want to slice contains arrays and when I use ControlDependenceOptions.NO_EXCEPTIONAL_EDGE.

**Comment by msridhar** [comment]
Can someone give more information on how to reproduce?  Input program, code to construct call graph, statement to slice from, etc.

**Comment by herda** [comment]
I am trying to use the WALA slicer as shown in this user guide:

http://wala.sourceforge.net/wiki/index.php/UserGuide:Slicer

It tries to create the backward slice of the main method using the first occurrence of a println statement. The problem is that as soon as I have an array in the code slicing takes a lot of time(never got one to finish) and also the exception described above is thrown. 

Also if you know a better way to slice using wala please tell me about it.  

This is the code I am trying to run:

```Java
public static Collection<Statement> doSlicing(String appJar, File exclusions) throws WalaException, IllegalArgumentException, CancelException, IOException {
		// create an analysis scope representing the appJar as a J2SE application
		System.out.println("Create Analysis scope");
		AnalysisScope scope = AnalysisScopeReader.makeJavaBinaryAnalysisScope(appJar,exclusions);
		System.out.println("Create class hierarchy");
		ClassHierarchy cha = ClassHierarchy.make(scope);
		System.out.println("Compute entry points");
		Iterable<Entrypoint> entrypoints = com.ibm.wala.ipa.callgraph.impl.Util.makeMainEntrypoints(scope, cha);
		AnalysisOptions options = new AnalysisOptions(scope, entrypoints);

		// build the call graph
		System.out.println("Build call graph");
		com.ibm.wala.ipa.callgraph.CallGraphBuilder cgb = Util.makeZeroCFABuilder(options, new AnalysisCache(),cha, scope, null, null);
		CallGraph cg = cgb.makeCallGraph(options, null);
		System.out.println("Create pointer analysis");
		PointerAnalysis pa = cgb.getPointerAnalysis();
		
		// find seed statement
		System.out.println("Find seed");
		Statement statement = findCallTo(findMainMethod(cg), "println");

		Collection<Statement> slice;
		System.out.println("Compute slice");
		
		DataDependenceOptions ddo = DataDependenceOptions.NO_EXCEPTIONS;
		slice = Slicer.computeBackwardSlice ( statement, cg, pa, ddo, ControlDependenceOptions.NO_EXCEPTIONAL_EDGES );
		
		return slice;

	}
```

And this is my input program:

```Java

package example;

import java.io.IOException;

public class Example {
	public static void main(String[] argv) throws IOException{
		int[] a = new int[3];
		int sum = 0;
		int i = 0;
		while (i < 3) {
			if (sum == 0)
				sum = sum+a[i];
			i = i+1;
		}
		System.out.println(sum);
	}
}

```


This is my exclusion file:
```
java\/awt\/.*
java\/crypto\/.*
java\/security\/.*
java\/util\/.*
javax\/swing\/.*
javax\/crypto\/.*
javax\/util\/.*
sun\/awt\/.*
sun\/swing\/.*
com\/sun\/.*
sun\/.*
com\/oracle\/.*
oracle\/.*
org\/netbeans\/.*
org\/openide\/.*
com\/ibm\/crypto\/.*
com\/ibm\/security\/.*
org\/apache\/xerces\/.*
dalvik\/.*
apple\/.*
com\/apple\/.*
jdk\/.*
org\/omg\/.*
org\/w3c\/.*
```

Thank you!
