### ISSUE TITLE
Demand Driven Analysis crashing on a few Inputs

### ISSUE THREAD

**Issue by akshayutture** [wala/WALA#907]
The Demand Driven Analysis from here 
(https://github.com/wala/WALA-start/blob/master/src/main/java/com/ibm/wala/examples/drivers/DemandPointsToDriver.java) 
crashes on a couple of the programs from the benchmark set I am working with.

Here is one such input jar. 
(https://drive.google.com/file/d/1_q55B0ALP-ygrAz4FsgL8Qmpw_Hb0w4C/view?usp=sharing )

Here is the error message
```
Exception in thread "main" java.lang.IllegalArgumentException: type is null
	at com.ibm.wala.ipa.callgraph.propagation.ConcreteTypeKey.<init>(ConcreteTypeKey.java:34)
	at com.ibm.wala.ipa.callgraph.propagation.ClassBasedInstanceKeys.getInstanceKeyForMetadataObject(ClassBasedInstanceKeys.java:141)
	at com.ibm.wala.ipa.callgraph.propagation.cfa.ZeroXInstanceKeys.getInstanceKeyForMetadataObject(ZeroXInstanceKeys.java:266)
	at com.ibm.wala.ipa.callgraph.propagation.PropagationCallGraphBuilder.getInstanceKeyForMetadataObject(PropagationCallGraphBuilder.java:755)
	at com.ibm.wala.demandpa.alg.ThisFilteringHeapModel.getInstanceKeyForMetadataObject(ThisFilteringHeapModel.java:62)
	at com.ibm.wala.demandpa.flowgraph.DemandPointerFlowGraph$StatementVisitor.visitLoadMetadata(DemandPointerFlowGraph.java:491)
	at com.ibm.wala.ssa.SSALoadMetadataInstruction.visit(SSALoadMetadataInstruction.java:64)
	at com.ibm.wala.demandpa.flowgraph.AbstractDemandFlowGraph.addBlockInstructionConstraints(AbstractDemandFlowGraph.java:278)
	at com.ibm.wala.demandpa.flowgraph.AbstractDemandFlowGraph.addNodeInstructionConstraints(AbstractDemandFlowGraph.java:263)
	at com.ibm.wala.demandpa.flowgraph.AbstractDemandFlowGraph.unconditionallyAddConstraintsFromNode(AbstractDemandFlowGraph.java:253)
	at com.ibm.wala.demandpa.flowgraph.AbstractDemandFlowGraph.addSubgraphForNode(AbstractDemandFlowGraph.java:94)
	at com.ibm.wala.demandpa.flowgraph.AbstractFlowGraph.getArrayWrites(AbstractFlowGraph.java:352)
	at com.ibm.wala.demandpa.flowgraph.AbstractFlowGraph.getWritesToInstanceField(AbstractFlowGraph.java:263)
	at com.ibm.wala.demandpa.alg.DemandRefinementPointsTo$PointsToComputer$1.visitGetField(DemandRefinementPointsTo.java:1260)
	at com.ibm.wala.demandpa.flowgraph.GetFieldLabel.visit(GetFieldLabel.java:84)
	at com.ibm.wala.demandpa.flowgraph.AbstractFlowGraph.visitSuccs(AbstractFlowGraph.java:166)
	at com.ibm.wala.demandpa.alg.DemandRefinementPointsTo$PointsToComputer.handleInitWorklist(DemandRefinementPointsTo.java:1277)
	at com.ibm.wala.demandpa.alg.DemandRefinementPointsTo$PointsToComputer.worklistLoop(DemandRefinementPointsTo.java:940)
	at com.ibm.wala.demandpa.alg.DemandRefinementPointsTo$PointsToComputer.compute(DemandRefinementPointsTo.java:932)
	at com.ibm.wala.demandpa.alg.DemandRefinementPointsTo.outerRefinementLoop(DemandRefinementPointsTo.java:339)
	at com.ibm.wala.demandpa.alg.DemandRefinementPointsTo.getPointsToWithStates(DemandRefinementPointsTo.java:276)
	at com.ibm.wala.demandpa.alg.DemandRefinementPointsTo.getPointsTo(DemandRefinementPointsTo.java:256)
	at DemandPointsToDriver.main(DemandPointsToDriver.java:96)
```

**Comment by msridhar** [comment]
Thanks for the report @akshayutture!  This is now fixed.

**Comment by akshayutture** [comment]
Thank you for the fix!
