### ISSUE TITLE
Flaky test failures on Ubuntu JDK 11

### ISSUE THREAD

**Issue by msridhar** [wala/WALA#916]
On CI, we occasionally get a test failure in `com.ibm.wala.core` only on JDK 11, with a stack like the following:
```
com.ibm.wala.core.tests.callGraph.CallGraphTest > testJava_cup FAILED
341
    java.lang.AssertionError
342
        at com.ibm.wala.util.intset.BitVectorIntSet$1.hasNext(BitVectorIntSet.java:228)
343
        at com.ibm.wala.ipa.callgraph.propagation.rta.DelegatingExplicitCallGraph$DelegatingEdgeManager.getPredNodeNumbers(DelegatingExplicitCallGraph.java:243)
344
        at com.ibm.wala.ipa.callgraph.impl.ExplicitCallGraph$ExplicitEdgeManager.getPredNodes(ExplicitCallGraph.java:374)
345
        at com.ibm.wala.ipa.callgraph.impl.ExplicitCallGraph$ExplicitEdgeManager.getPredNodes(ExplicitCallGraph.java:343)
346
        at com.ibm.wala.util.graph.AbstractGraph.getPredNodes(AbstractGraph.java:66)
347
        at com.ibm.wala.util.graph.GraphIntegrity.checkEdges(GraphIntegrity.java:90)
348
        at com.ibm.wala.util.graph.GraphIntegrity.check(GraphIntegrity.java:41)
349
        at com.ibm.wala.core.tests.callGraph.CallGraphTest.doCallGraphs(CallGraphTest.java:408)
350
        at 
```
I do not know how this could be failing only on JDK 11.  I will try updating the JDK used in CI to see if it goes away due to a fixed JVM bug.  If it doesn't, I will have to investigate further.

**Comment by msridhar** [comment]
Update: #917 did not fix this problem.  I also cannot reproduce on Mac.  It may be a combination of a WALA bug and some non-determinism that is only getting exposed on Linux.  It's a tough one to debug.

**Comment by liblit** [comment]
Should we consider disabling this test when running on Java 11 until the problem can be fixed? This non-deterministic failure creates a speed bump for other changes: we need to rerun *all* GitHub CI jobs until we get lucky for this one flaky test.

**Comment by msridhar** [comment]
The problem is it's not always the same test that fails.  In the example above, it was `test_Javacup`, but in the CI job that failed for #954 it was `testOcamlHash`.  We could try disabling both of these on Java 11 for now, I guess.

I really wish I had a way to repro this one.  I tried installing WALA in an Ubuntu Docker container on my Mac and running `testOcamlHash` several times, but never saw a failure.

**Comment by msridhar** [comment]
I haven't seen these failures in a while; hopefully a JDK update fixed it.  Closing until we see it again
