### ISSUE TITLE
A question about wala slicing options

### ISSUE THREAD

**Issue by anabioticsoul** [wala/WALA#967]
It has occurred a problem **unimpementedError** with **NO_INTERPROC_EDGES** control dependence options.

```
"C:\Program Files\Java\jdk-16.0.1\bin\java.exe" "-javaagent:D:\program files\JetBrains\IntelliJ IDEA 2020.2.3\lib\idea_rt.jar=60152:D:\program files\JetBrains\IntelliJ IDEA 2020.2.3\bin" -Dfile.encoding=UTF-8 -classpath E:\JavaProjectRepositories\conf_locator\out\production\conf_locator;E:\JavaProjectRepositories\conf_locator\lib\com.ibm.wala.cast-1.5.8-SNAPSHOT.jar;E:\JavaProjectRepositories\conf_locator\lib\com.ibm.wala.core-1.5.8-SNAPSHOT.jar;E:\JavaProjectRepositories\conf_locator\lib\com.ibm.wala.util-1.5.8-SNAPSHOT.jar;E:\JavaProjectRepositories\conf_locator\lib\com.ibm.wala.shrike-1.5.8-SNAPSHOT.jar;E:\JavaProjectRepositories\conf_locator\lib\com.ibm.wala.cast.java-1.5.8-SNAPSHOT.jar;E:\JavaProjectRepositories\conf_locator\tests\test.jar;E:\JavaProjectRepositories\conf_locator\tests\hadoop-hdfs-2.10.1.jar;E:\JavaProjectRepositories\conf_locator\tests\hadoop-hdfs-nfs-2.10.1.jar;E:\JavaProjectRepositories\conf_locator\tests\hadoop-hdfs-rbf-2.10.1.jar;E:\JavaProjectRepositories\conf_locator\tests\hadoop-hdfs-client-2.10.1.jar;E:\JavaProjectRepositories\conf_locator\tests\hadoop-hdfs-native-client-2.10.1.jar TestCase
Call Graph Nodes: 7613
methodName:< Application, Lorg/apache/hadoop/hdfs/server/namenode/FSImage, recoverStorageDirs(Lorg/apache/hadoop/hdfs/server/common/HdfsServerConstants$StartupOption;Lorg/apache/hadoop/hdfs/server/namenode/NNStorage;Ljava/util/Map;)Z >
srcMethodName:recoverStorageDirs
Exception in thread "main" com.ibm.wala.util.debug.UnimplementedError
	at com.ibm.wala.util.debug.Assertions.productionAssertion(Assertions.java:37)
	at com.ibm.wala.ipa.slicer.PDG.createControlDependenceEdges(PDG.java:267)
	at com.ibm.wala.ipa.slicer.PDG.createScalarEdges(PDG.java:200)
	at com.ibm.wala.ipa.slicer.PDG.populate(PDG.java:193)
	at com.ibm.wala.ipa.slicer.PDG.iterator(PDG.java:1216)
	at com.ibm.wala.ipa.slicer.SDG.addPDGStatementNodes(SDG.java:175)
	at com.ibm.wala.ipa.slicer.SDG.eagerConstruction(SDG.java:166)
	at com.ibm.wala.ipa.slicer.SDG.access$200(SDG.java:56)
	at com.ibm.wala.ipa.slicer.SDG$Nodes.getMaxNumber(SDG.java:215)
	at com.ibm.wala.util.graph.AbstractNumberedGraph.getMaxNumber(AbstractNumberedGraph.java:36)
	at com.ibm.wala.ipa.slicer.thin.CISDG.getMaxNumber(CISDG.java:100)
	at com.ibm.wala.util.graph.AbstractNumberedGraph.getMaxNumber(AbstractNumberedGraph.java:36)
	at com.ibm.wala.util.graph.traverse.NumberedDFSFinishTimeIterator.<init>(NumberedDFSFinishTimeIterator.java:55)
	at com.ibm.wala.util.graph.traverse.DFS.iterateFinishTime(DFS.java:207)
	at com.ibm.wala.util.graph.traverse.DFS.getReachableNodes(DFS.java:69)
	at com.ibm.wala.ipa.slicer.thin.CISlicer.computeBackwardThinSlice(CISlicer.java:95)
	at ConfigurationSlicer.performSlicing(ConfigurationSlicer.java:211)
	at TestCase.main(TestCase.java:47)

Process finished with exit code 1
```

I have read the source code of class PDG, the assertion is found in createControlDependenceEdges() method. Does this code mean that the **NO_INTERPROC_EDGES** option always throws Exception?(**Assertions.productionAssertion(cOptions.equals(ControlDependenceOptions.FULL));**)

```
if (cOptions.isIgnoreExceptions()) {
                    PrunedCFG<SSAInstruction, ISSABasicBlock> prunedCFG = ExceptionPrunedCFG.make((ControlFlowGraph)controlFlowGraph);
                    if (prunedCFG.getNumberOfNodes() == 2 && prunedCFG.containsNode(((ControlFlowGraph)controlFlowGraph).entry()) && prunedCFG.containsNode(((ControlFlowGraph)controlFlowGraph).exit()) && GraphUtil.countEdges(prunedCFG) == 0L) {
                        return;
                    }

                    controlFlowGraph = prunedCFG;
                } else {
                    Assertions.productionAssertion(cOptions.equals(ControlDependenceOptions.FULL));
                }
```

**Comment by msridhar** [comment]
Thanks for the report!  The assertion looks wrong to me, so I'm removing it.  This issue will be closed when the change lands.

**Comment by anabioticsoul** [comment]
Thank you very much!
